force-app/main/default/objects/BulkProcessLog__c/BulkProcessLog__c.object-meta.xml
<CustomObject>
    <label>一括処理ログ</label>
    <nameField>
        <displayFormat>BPL-{0000000000}</displayFormat>
        <label>一括処理ログ#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BulkProcessLog__c/fields/DispatchDetail__c.field-meta.xml
<CustomField>
    <fullName>DispatchDetail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>配車明細</label>
    <referenceTo>DispatchDetail__c</referenceTo>
    <relationshipLabel>一括処理ログ</relationshipLabel>
    <relationshipName>DispatchDetailList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BulkProcessLog__c/fields/ProcessDetails__c.field-meta.xml
<CustomField>
    <fullName>ProcessDetails__c</fullName>
    <label>処理内容</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BulkProcessLog__c/fields/ProcessStatus__c.field-meta.xml
<CustomField>
    <fullName>ProcessStatus__c</fullName>
    <label>処理状態</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Start</fullName>
                <label>処理開始</label>
            </value>
            <value>
                <fullName>Processing</fullName>
                <label>処理中</label>
            </value>
            <value>
                <fullName>Success</fullName>
                <label>正常終了</label>
            </value>
            <value>
                <fullName>Error</fullName>
                <label>異常終了</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BulkProcessLog__c/fields/ProcessSubject__c.field-meta.xml
<CustomField>
    <fullName>ProcessSubject__c</fullName>
    <label>処理件名</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BulkProcessLog__c/fields/ProcessType__c.field-meta.xml
<CustomField>
    <fullName>ProcessType__c</fullName>
    <label>処理分類</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AutoGenWeeklyOffSchedule</fullName>
                <label>定休日勤務情報の自動生成</label>
            </value>
            <value>
                <fullName>UpsertScheduleByChangeWeeklyOff</fullName>
                <label>定休日変更時勤務情報変動</label>
            </value>
            <value>
                <fullName>CreateOrderFromRegularServiceBatch</fullName>
                <label>定期便注文作成バッチ</label>
            </value>
            <value>
                <fullName>RecordManualUpdate</fullName>
                <label>レコードの手動更新</label>
            </value>
            <value>
                <fullName>ImportFujiechoFareDetail</fullName>
                <label>富士エコー運賃明細インポート</label>
            </value>
            <value>
                <fullName>CreateShippingSalesReportBatch</fullName>
                <label>運賃売上日報作成バッチ</label>
            </value>
            <value>
                <fullName>StorageFeeAccountingDetailCreateBatch</fullName>
                <label>保管料の請求・支払明細作成のバッチ</label>
            </value>
            <value>
                <fullName>ImportTumixAttendance</fullName>
                <label>TUMIX出勤実績インポート</label>
            </value>
            <value>
                <fullName>OrderHeaderRelatedRecordsRollback</fullName>
                <label>注文の関連レコードのロールバック</label>
            </value>
            <value>
                <fullName>ShippingSalesReportOutputCtrl</fullName>
                <label>運送売上実績表PDF出力</label>
            </value>
            <value>
                <fullName>ShippedScheduleBatch</fullName>
            </value>
            <value>
                <fullName>ArrivedScheduleBatch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DispatchDetail__c/DispatchDetail__c.object-meta.xml
<CustomObject>
    <label>配車明細</label>
    <nameField>
        <displayFormat>DED-{00000000}</displayFormat>
        <label>配車明細#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchDetail__c/fields/ManualUpdateDatetime__c.field-meta.xml
<CustomField>
    <fullName>ManualUpdateDatetime__c</fullName>
    <label>手動更新日時</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DispatchDetail__c/fields/ManualUpdateNote__c.field-meta.xml
<CustomField>
    <fullName>ManualUpdateNote__c</fullName>
    <label>手動更新メモ</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/DispatchDetailTriggerHandler.cls
public inherited sharing class DispatchDetailTriggerHandler extends CommonTriggerHandler {
    private List<DispatchDetail__c> oldList;
    private List<DispatchDetail__c> newList;
    private Map<Id, DispatchDetail__c> oldMap;
    private Map<Id, DispatchDetail__c> newMap;

    public DispatchDetailTriggerHandler() {
        this.oldList = (List<DispatchDetail__c>) Trigger.old;
        this.newList = (List<DispatchDetail__c>) Trigger.new;
        this.oldMap = (Map<Id, DispatchDetail__c>) Trigger.oldMap;
        this.newMap = (Map<Id, DispatchDetail__c>) Trigger.newMap;
    }

    public override void beforeUpdate() {
        this.insertManualUpdateLog();
    }
    // 手動更新実行時、手動更新メモを一括処理ログに残し、項目をリセット。
    private void insertManualUpdateLog() {
        List<BulkProcessLog__c> bulkProcessList = new List<BulkProcessLog__c>();

        for (DispatchDetail__c dispatchDetailNew : this.newList) {
            if (dispatchDetailNew.ManualUpdateDatetime__c != this.oldMap.get(dispatchDetailNew.Id).ManualUpdateDatetime__c) {
                BulkProcessLog__c bulkProcess = new BulkProcessLog__c();
                bulkProcess.ProcessSubject__c = '配車明細レコードの手動更新';
                bulkProcess.ProcessStatus__c = 'Success';
                bulkProcess.ProcessType__c = 'RecordManualUpdate';
                bulkProcess.DispatchDetail__c = dispatchDetailNew.Id;
                bulkProcess.ProcessDetails__c = '手動更新メモ: ' + dispatchDetailNew.ManualUpdateNote__c;

                // 手動更新メモを削除
                dispatchDetailNew.ManualUpdateNote__c = null;

                bulkProcessList.add(bulkProcess);
            }
        }

        // 一括処理ログにinsert
        insert bulkProcessList;
    }
}