force-app/main/default/objects/BulkProcessLog__c/BulkProcessLog__c.object-meta.xml
<CustomObject>
    <label>一括処理ログ</label>
    <nameField>
        <displayFormat>BPL-{0000000000}</displayFormat>
        <label>一括処理ログ#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BulkProcessLog__c/fields/ProcessLog__c.field-meta.xml
<CustomField>
    <fullName>ProcessLog__c</fullName>
    <label>処理ログ</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BulkProcessLog__c/fields/ProcessStatus__c.field-meta.xml
<CustomField>
    <fullName>ProcessStatus__c</fullName>
    <label>処理状態</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Start</fullName>
                <label>処理開始</label>
            </value>
            <value>
                <fullName>Processing</fullName>
                <label>処理中</label>
            </value>
            <value>
                <fullName>Success</fullName>
                <label>正常終了</label>
            </value>
            <value>
                <fullName>Error</fullName>
                <label>異常終了</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BulkProcessLog__c/fields/ProcessSubject__c.field-meta.xml
<CustomField>
    <fullName>ProcessSubject__c</fullName>
    <label>処理件名</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MFJSetting__mdt/MFJSetting__mdt.object-meta.xml
<CustomObject>
    <label>マルエス環境変数</label>
</CustomObject>

force-app/main/default/objects/MFJSetting__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <inlineHelpText>フラグの場合 True/False を入力してください</inlineHelpText>
    <label>値</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OriginDestination__c/OriginDestination__c.object-meta.xml
<CustomObject>
    <label>発着地</label>
    <nameField>
        <label>発着地名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OriginDestination__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>市区郡</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OriginDestination__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>緯度</label>
    <precision>10</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OriginDestination__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>経度</label>
    <precision>11</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OriginDestination__c/fields/PrefectureLabel_F__c.field-meta.xml
<CustomField>
    <fullName>PrefectureLabel_F__c</fullName>
    <formula>CASE(
    Prefecture__c,
    &quot;1&quot;, &quot;北海道&quot;,
    &quot;2&quot;, &quot;青森県&quot;,
    &quot;3&quot;, &quot;岩手県&quot;,
    &quot;4&quot;, &quot;宮城県&quot;,
    &quot;5&quot;, &quot;秋田県&quot;,
    &quot;6&quot;, &quot;山形県&quot;,
    &quot;7&quot;, &quot;福島県&quot;,
    &quot;8&quot;, &quot;茨城県&quot;,
    &quot;9&quot;, &quot;栃木県&quot;,
    &quot;10&quot;, &quot;群馬県&quot;,
    &quot;11&quot;, &quot;埼玉県&quot;,
    &quot;12&quot;, &quot;千葉県&quot;,
    &quot;13&quot;, &quot;東京都&quot;,
    &quot;14&quot;, &quot;神奈川県&quot;,
    &quot;15&quot;, &quot;新潟県&quot;,
    &quot;16&quot;, &quot;富山県&quot;,
    &quot;17&quot;, &quot;石川県&quot;,
    &quot;18&quot;, &quot;福井県&quot;,
    &quot;19&quot;, &quot;山梨県&quot;,
    &quot;20&quot;, &quot;長野県&quot;,
    &quot;21&quot;, &quot;岐阜県&quot;,
    &quot;22&quot;, &quot;静岡県&quot;,
    &quot;23&quot;, &quot;愛知県&quot;,
    &quot;24&quot;, &quot;三重県&quot;,
    &quot;25&quot;, &quot;滋賀県&quot;,
    &quot;26&quot;, &quot;京都府&quot;,
    &quot;27&quot;, &quot;大阪府&quot;,
    &quot;28&quot;, &quot;兵庫県&quot;,
    &quot;29&quot;, &quot;奈良県&quot;,
    &quot;30&quot;, &quot;和歌山県&quot;,
    &quot;31&quot;, &quot;鳥取県&quot;,
    &quot;32&quot;, &quot;島根県&quot;,
    &quot;33&quot;, &quot;岡山県&quot;,
    &quot;34&quot;, &quot;広島県&quot;,
    &quot;35&quot;, &quot;山口県&quot;,
    &quot;36&quot;, &quot;徳島県&quot;,
    &quot;37&quot;, &quot;香川県&quot;,
    &quot;38&quot;, &quot;愛媛県&quot;,
    &quot;39&quot;, &quot;高知県&quot;,
    &quot;40&quot;, &quot;福岡県&quot;,
    &quot;41&quot;, &quot;佐賀県&quot;,
    &quot;42&quot;, &quot;長崎県&quot;,
    &quot;43&quot;, &quot;熊本県&quot;,
    &quot;44&quot;, &quot;大分県&quot;,
    &quot;45&quot;, &quot;宮崎県&quot;,
    &quot;46&quot;, &quot;鹿児島県&quot;,
    &quot;47&quot;, &quot;沖縄県&quot;,
    &quot;&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>都道府県（ラベル）</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OriginDestination__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>町村（町名）</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MapAPIHandler.cls
public class MapAPIHandler implements Queueable, Database.AllowsCallouts {
    // APIキー
    private static final String apiKey = MFJSetting__mdt.getInstance('MapApiKey').Value__c;
    private OriginDestination__c originDestination;

    @InvocableMethod(label='座標設定' description='緯度と経度を取得')
    public static void setCoordinatesInvocable(List<OriginDestination__c> records) {
        if (records.isEmpty())
            return;

        for (OriginDestination__c record : records) {
            System.enqueueJob(new MapAPIHandler(record));
        }
    }

    // コンストラクタ：対象の発着地レコードを受け取り、インスタンスに保持する
    public MapAPIHandler(OriginDestination__c originDestination) {
        this.originDestination = originDestination;
    }

    // Queueableジョブ実行時に呼ばれるメソッド。非同期で座標設定を実行する
    // Google Maps APIを使って住所から緯度・経度を取得し、レコードに設定・更新する
    public void execute(QueueableContext context) {
        // 発着地レコードがない場合、または住所の項目に値がない場合、処理しない
        if (this.originDestination == null)
            return;

        // 住所＝{都道府県}、{市区郡}、{町村（町名）}
        String address =
            '日本、' +
            this.originDestination.PrefectureLabel_F__c +
            '、' +
            this.originDestination.City__c +
            '、' +
            this.originDestination.Street__c;

        HttpRequest req = new HttpRequest();
        // APIのエンドポイント
        String endpoint =
            'https://maps.googleapis.com/maps/api/geocode/' +
            // 結果の形
            'json' +
            '?' +
            // 住所
            'address=' +
            address +
            // 言語＝日本語
            '&language=ja' +
            // APIキー
            '&key=' +
            apiKey;
        req.setEndpoint(endpoint);
        req.setMethod('GET');

        try {
            Http http = new Http();
            // APIリクエストを送って、レスポンスを取得する
            HttpResponse res = http.send(req);
            Map<String, Object> resMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());

            // レスポンスの状態が成功の場合、レコードの緯度と経度が設定される
            if (res.getStatusCode() == 200 && resMap.get('status') == 'OK') {
                List<Object> results = (List<Object>) resMap.get('results');
                if (!results.isEmpty()) {
                    Map<String, Object> location = (Map<String, Object>) ((Map<String, Object>) ((Map<String, Object>) results[0])
                            .get('geometry'))
                        .get('location');

                    this.originDestination.Latitude__c = (Decimal) location.get('lat');
                    this.originDestination.Longitude__c = (Decimal) location.get('lng');

                    // レコードの更新
                    update this.originDestination;
                } else {
                    throw new CommonTriggerHandler.MyException('経度緯度取得できません: ' + address);
                }
            } else {
                throw new CommonTriggerHandler.MyException('Google Maps APIエラー: ' + resMap.get('error_message'));
            }
        } catch (Exception e) {
            System.debug('緯度と経度を取得するAPI: ' + e.getMessage() + '\n' + e.getStackTraceString());
            BulkProcessLog__c processLog = new BulkProcessLog__c();
            processLog.ProcessSubject__c = '緯度と経度を取得するAPIにおいてエラーが発生しました';
            processLog.ProcessStatus__c = 'Error';
            processLog.ProcessLog__c = e.getMessage() + '\n' + e.getStackTraceString();
            Database.insert(processLog);
        }
    }
}