force-app/main/default/objects/BulkProcessLog__c/BulkProcessLog__c.object-meta.xml
<CustomObject>
    <label>一括処理ログ</label>
    <nameField>
        <displayFormat>BPL-{0000000000}</displayFormat>
        <label>一括処理ログ#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BulkProcessLog__c/fields/ProcessDetails__c.field-meta.xml
<CustomField>
    <fullName>ProcessDetails__c</fullName>
    <label>処理内容</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BulkProcessLog__c/fields/ProcessStatus__c.field-meta.xml
<CustomField>
    <fullName>ProcessStatus__c</fullName>
    <label>処理状態</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Start</fullName>
                <label>処理開始</label>
            </value>
            <value>
                <fullName>Processing</fullName>
                <label>処理中</label>
            </value>
            <value>
                <fullName>Success</fullName>
                <label>正常終了</label>
            </value>
            <value>
                <fullName>Error</fullName>
                <label>異常終了</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BulkProcessLog__c/fields/ProcessSubject__c.field-meta.xml
<CustomField>
    <fullName>ProcessSubject__c</fullName>
    <label>処理件名</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BulkProcessLog__c/fields/ProcessType__c.field-meta.xml
<CustomField>
    <fullName>ProcessType__c</fullName>
    <label>処理分類</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AutoGenWeeklyOffSchedule</fullName>
                <label>定休日勤務情報の自動生成</label>
            </value>
            <value>
                <fullName>UpsertScheduleByChangeWeeklyOff</fullName>
                <label>定休日変更時勤務情報変動</label>
            </value>
            <value>
                <fullName>CreateOrderFromRegularServiceBatch</fullName>
                <label>定期便注文作成バッチ</label>
            </value>
            <value>
                <fullName>RecordManualUpdate</fullName>
                <label>レコードの手動更新</label>
            </value>
            <value>
                <fullName>ImportFujiechoFareDetail</fullName>
                <label>富士エコー運賃明細インポート</label>
            </value>
            <value>
                <fullName>CreateShippingSalesReportBatch</fullName>
                <label>運賃売上日報作成バッチ</label>
            </value>
            <value>
                <fullName>StorageFeeAccountingDetailCreateBatch</fullName>
                <label>保管料の請求・支払明細作成のバッチ</label>
            </value>
            <value>
                <fullName>ImportTumixAttendance</fullName>
                <label>TUMIX出勤実績インポート</label>
            </value>
            <value>
                <fullName>OrderHeaderRelatedRecordsRollback</fullName>
                <label>注文の関連レコードのロールバック</label>
            </value>
            <value>
                <fullName>ShippingSalesReportOutputCtrl</fullName>
                <label>運送売上実績表PDF出力</label>
            </value>
            <value>
                <fullName>ShippedScheduleBatch</fullName>
            </value>
            <value>
                <fullName>ArrivedScheduleBatch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BulkProcessLog__c/fields/ToEmailGroupAddresses__c.field-meta.xml
<CustomField>
    <fullName>ToEmailGroupAddresses__c</fullName>
    <label>送信先の課</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OrderGroup</fullName>
                <label>受注課</label>
            </value>
            <value>
                <fullName>DispatchGroup</fullName>
                <label>配車課</label>
            </value>
            <value>
                <fullName>SystemGroup</fullName>
                <label>システム課</label>
            </value>
            <value>
                <fullName>AccountingGroup</fullName>
                <label>経理課</label>
            </value>
            <value>
                <fullName>WarehouseGroup</fullName>
                <label>倉庫課</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ObjectiveManagement__c/ObjectiveManagement__c.object-meta.xml
<CustomObject>
    <label>目標管理</label>
    <nameField>
        <label>目標管理名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjectiveManagement__c/fields/FirstTermSalesTarget__c.field-meta.xml
<CustomField>
    <fullName>FirstTermSalesTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>第1期目標</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ObjectiveManagement__c/fields/ObjectiveManagement__c.field-meta.xml
<CustomField>
    <fullName>ObjectiveManagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>目標管理</label>
    <referenceTo>ObjectiveManagement__c</referenceTo>
    <relationshipLabel>目標管理</relationshipLabel>
    <relationshipName>ObjectiveManagementList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ObjectiveManagement__c/fields/SameMonthLastYearTotalSales_F__c.field-meta.xml
<CustomField>
    <fullName>SameMonthLastYearTotalSales_F__c</fullName>
    <formula>IF (  ISBLANK(ObjectiveManagement__c)  ,  SameMonthLastYearTotalSales__c ,  ObjectiveManagement__r.TotalSales_Sum__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>前年同月実績</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ObjectiveManagement__c/fields/SecondTermSalesTarget__c.field-meta.xml
<CustomField>
    <fullName>SecondTermSalesTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>第2期目標</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ObjectiveManagement__c/fields/ThirdTermSalesTarget__c.field-meta.xml
<CustomField>
    <fullName>ThirdTermSalesTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>第3期目標</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/ShippingSalesReport__c.object-meta.xml
<CustomObject>
    <label>運送売上実績表</label>
    <nameField>
        <displayFormat>DSS-{0000000000}</displayFormat>
        <label>運送売上実績表#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ShippingSalesReport__c/fields/ChateraiseSales__c.field-meta.xml
<CustomField>
    <fullName>ChateraiseSales__c</fullName>
    <label>シャトレーゼ実績</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/ChateraiseSubcontractorSales__c.field-meta.xml
<CustomField>
    <fullName>ChateraiseSubcontractorSales__c</fullName>
    <label>シャトレーゼ下払い</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>日付マスタ</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/FujiEchoCharteredVehicleSubcontractSales__c.field-meta.xml
<CustomField>
    <fullName>FujiEchoCharteredVehicleSubcontractSales__c</fullName>
    <label>富士エコー・ローソン（傭車）下払い</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/FujiEchoSales_F__c.field-meta.xml
<CustomField>
    <fullName>FujiEchoSales_F__c</fullName>
    <formula>FujiEchoMfjVehicleSales__c+FujiEchoCharteredVehicleSales__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>富士エコー・ローソン(売上細目)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/GeneralSales_F__c.field-meta.xml
<CustomField>
    <fullName>GeneralSales_F__c</fullName>
    <formula>MARUSMfjVehicleSales__c - FujiEchoMfjVehicleSales__c + CharteredVehicleSales__c - FujiEchoCharteredVehicleSales__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>一般(売上細目)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/GeneralSalesSubcontractorSales_F__c.field-meta.xml
<CustomField>
    <fullName>GeneralSalesSubcontractorSales_F__c</fullName>
    <formula>/*対応未完了*/
CharteredVehicleSubcontractorSales__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>一般(下払い金額)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/ObjectiveManagement__c.field-meta.xml
<CustomField>
    <fullName>ObjectiveManagement__c</fullName>
    <label>目標管理</label>
    <referenceTo>ObjectiveManagement__c</referenceTo>
    <relationshipName>ShippingSalesReport</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/TotalSales_F__c.field-meta.xml
<CustomField>
    <fullName>TotalSales_F__c</fullName>
    <formula>GeneralSales_F__c + ChateraiseSales__c + FujiEchoSales_F__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>全体合計(売上細目)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/TotalSubcontractorSales_F__c.field-meta.xml
<CustomField>
    <fullName>TotalSubcontractorSales_F__c</fullName>
    <formula>GeneralSalesSubcontractorSales_F__c + ChateraiseSubcontractorSales__c + FujiEchoCharteredVehicleSubcontractSales__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>全体合計(下払い金額)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ShippingSalesReportOutputCtrl.cls
public with sharing class ShippingSalesReportOutputCtrl {
    public Id recordId { get; set; }
    public String errorMessage { get; private set; }
    public Boolean hasError { get; private set; }
    public ShippingSalesReport__c report { get; set; }
    public String formattedDate { get; set; } //日付
    public String formattedWeekday { get; set; } //曜日
    public Integer phase { get; set; } //期
    public Decimal phase1Actual { get; set; } //1期実績
    public Decimal phase2Actual { get; set; } //2期実績
    public Decimal phase3Actual { get; set; } //3期実績
    public Decimal monthActual { get; set; } //当月実績
    public Decimal monthTarget { get; set; } //当月目標
    public Decimal phase1AchievementRate { get; set; } //1期達成率
    public Decimal phase2AchievementRate { get; set; } //2期達成率
    public Decimal phase3AchievementRate { get; set; } //3期達成率
    public Decimal monthAchievementRate { get; set; } //当月達成率
    public Decimal lastYearSameMonthRate { get; set; } //前年同月比
    public Decimal TotalBalance { get; set; } //全体合計(差額)
    public Decimal GeneralBalance { get; set; } //一般(差額)
    public Decimal ChateraiseBalance { get; set; } //シャトレーゼ(差額)
    public Decimal FujiEchoBalance { get; set; } //富士エコー・ローソン(差額)
    public Decimal GeneralSalesPercent { get; set; } //占有率(一般)(売上細目)
    public Decimal ChateraiseSalesPercent { get; set; } //占有率(シャトレーゼ)(売上細目)
    public Decimal FujiEchoSalesPercent { get; set; } //占有率(富士エコー・ローソン)(売上細目)
    public Decimal TotalSalesPercent { get; set; } //占有率(全体合計)(売上細目)
    public Decimal GeneralPaymentPercent { get; set; } //占有率(一般)(下払い金額)
    public Decimal ChateraisePaymentPercent { get; set; } //占有率(シャトレーゼ)(下払い金額)
    public Decimal FujiEchoPaymentPercent { get; set; } //占有率(富士エコー・ローソン)(下払い金額)
    public Decimal TotalPaymentPercent { get; set; } //占有率(全体合計)(下払い金額)
    public Decimal GeneralBalancePercent { get; set; } //占有率(一般)(差額)
    public Decimal ChateraiseBalancePercent { get; set; } //占有率(シャトレーゼ)(差額)
    public Decimal FujiEchoBalancePercent { get; set; } //占有率(富士エコー・ローソン)(差額)
    public Decimal TotalBalancePercent { get; set; } //占有率(全体合計)(差額)

    private Integer year;
    public Integer month { get; set; }
    private Integer day;

    public ShippingSalesReportOutputCtrl(ApexPages.StandardController controller) {
        try {
            this.hasError = false;
            this.recordId = ApexPages.currentPage().getParameters().get('id');
            Date outputDay = Date.today();
            if (String.isNotBlank(recordId)) {
                List<ShippingSalesReport__c> report = [
                    SELECT Id, Date__c
                    FROM ShippingSalesReport__c
                    WHERE Id = :this.recordId
                    LIMIT 1
                ];
                if (!report.isEmpty()) {
                    outputDay = report[0].Date__c;
                }
            }

            String formattedDate = String.valueOf(outputDay).replace('-', '') + '_' + System.now().format('yyyyMMddHHmmss');
            String encodedFileName = EncodingUtil.urlEncode('日報売上実績表_' + formattedDate + '.pdf', 'UTF-8');
            String contentDispositionHeader = 'inline; filename*=UTF-8\'\'' + encodedFileName;
            ApexPages.currentPage().getHeaders().put('content-disposition', contentDispositionHeader);
        } catch (Exception ex) {
            this.hasError = true;
            errorMessage = '処理中に予期しないエラーが発生しました。<br/>お手数ですが、システム管理者までご連絡をお願いいたします。';
        }
    }

    public PageReference init() {
        try {
            if (this.hasError) {
                BulkProcessLog__c processLog = new BulkProcessLog__c(
                    ProcessSubject__c = '運送売上実績表PDF出力時エラー発生通知',
                    ProcessDetails__c = errorMessage,
                    ProcessStatus__c = 'Error',
                    ProcessType__c = 'ShippingSalesReportOutputCtrl',
                    ToEmailGroupAddresses__c = 'SystemGroup'
                );
                insert processLog;
                return null;
            }
            if (String.isNotBlank(recordId)) {
                List<ShippingSalesReport__c> reportList = [
                    SELECT
                        Id,
                        Name,
                        Date__c, //日付
                        GeneralSales_F__c, //一般(売上細目)
                        ChateraiseSales__c, //シャトレーゼ(売上細目)
                        FujiEchoSales_F__c, //富士エコー・ローソン(売上細目)
                        TotalSales_F__c, //全体合計(売上細目)
                        TotalSubcontractorSales_F__c, //全体合計(下払い金額)
                        GeneralSalesSubcontractorSales_F__c, //一般(下払い金額)
                        ChateraiseSubcontractorSales__c, //シャトレーゼ(下払い金額)
                        FujiEchoCharteredVehicleSubcontractSales__c, //富士エコー・ローソン(下払い金額)
                        ObjectiveManagement__r.FirstTermSalesTarget__c, //第1期目標
                        ObjectiveManagement__r.SecondTermSalesTarget__c, //第2期目標
                        ObjectiveManagement__r.ThirdTermSalesTarget__c, //第3期目標
                        ObjectiveManagement__r.SameMonthLastYearTotalSales_F__c //前年同月実績
                    FROM ShippingSalesReport__c
                    WHERE Id = :recordId
                    LIMIT 1
                ];

                if (!reportList.isEmpty()) {
                    report = reportList[0];
                    if (report.Date__c != null) {
                        year = report.Date__c.year();
                        month = report.Date__c.month();
                        day = report.Date__c.day();
                        phase = getPhase(report.Date__c);
                        formattedDate = year + '年' + month + '月' + day + '日';
                        Datetime dt = (Datetime) report.Date__c;
                        String dayOfWeek = dt.format('u');
                        formattedWeekday = weekdayMap.get(Integer.valueOf(dayOfWeek)); //曜日
                        TotalBalance = report.TotalSales_F__c - report.TotalSubcontractorSales_F__c; //全体合計(差額)

                        GeneralBalance = report.GeneralSales_F__c - report.GeneralSalesSubcontractorSales_F__c; //一般(差額)
                        ChateraiseBalance = report.ChateraiseSales__c - report.ChateraiseSubcontractorSales__c; //シャトレーゼ(差額)
                        FujiEchoBalance = report.FujiEchoSales_F__c - report.FujiEchoCharteredVehicleSubcontractSales__c; //富士エコー・ローソン(差額)

                        GeneralSalesPercent = calculatePercentage(report.GeneralSales_F__c, report.TotalSales_F__c); //占有率(一般)(売上細目)
                        ChateraiseSalesPercent = calculatePercentage(report.ChateraiseSales__c, report.TotalSales_F__c); //占有率(シャトレーゼ)(売上細目)
                        FujiEchoSalesPercent = calculatePercentage(report.FujiEchoSales_F__c, report.TotalSales_F__c); //占有率(富士エコー・ローソン)(売上細目)
                        TotalSalesPercent = GeneralSalesPercent + ChateraiseSalesPercent + FujiEchoSalesPercent; //占有率(全体合計)(売上細目)

                        GeneralPaymentPercent = calculatePercentage(
                            report.GeneralSalesSubcontractorSales_F__c,
                            report.TotalSubcontractorSales_F__c
                        ); //占有率(一般)(下払い金額)
                        ChateraisePaymentPercent = calculatePercentage(
                            report.ChateraiseSubcontractorSales__c,
                            report.TotalSubcontractorSales_F__c
                        ); //占有率(シャトレーゼ)(下払い金額)
                        FujiEchoPaymentPercent = calculatePercentage(
                            report.FujiEchoCharteredVehicleSubcontractSales__c,
                            report.TotalSubcontractorSales_F__c
                        ); //占有率(富士エコー・ローソン)(下払い金額)
                        TotalPaymentPercent = GeneralPaymentPercent + ChateraisePaymentPercent + FujiEchoPaymentPercent; //占有率(全体合計)(下払い金額)

                        GeneralBalancePercent = calculatePercentage(GeneralBalance, TotalBalance); //占有率(一般)(差額)
                        ChateraiseBalancePercent = calculatePercentage(ChateraiseBalance, TotalBalance); //占有率(シャトレーゼ)(差額)
                        FujiEchoBalancePercent = calculatePercentage(FujiEchoBalance, TotalBalance); //占有率(富士エコー・ローソン)(差額)
                        TotalBalancePercent = GeneralBalancePercent + ChateraiseBalancePercent + FujiEchoBalancePercent; //占有率(全体合計)(差額)

                        phase1Actual = getPhaseActual(1, year, month); //1期実績
                        phase2Actual = getPhaseActual(2, year, month); //2期実績
                        phase3Actual = getPhaseActual(3, year, month); //3期実績
                        monthActual = getPhaseActual(0, year, month); //今月売上実績
                        monthTarget =
                            report.ObjectiveManagement__r.FirstTermSalesTarget__c +
                            report.ObjectiveManagement__r.SecondTermSalesTarget__c +
                            report.ObjectiveManagement__r.ThirdTermSalesTarget__c;
                        phase1AchievementRate = calculatePercentage(
                            phase1Actual,
                            report.ObjectiveManagement__r.FirstTermSalesTarget__c
                        );
                        phase2AchievementRate = calculatePercentage(
                            phase2Actual,
                            report.ObjectiveManagement__r.SecondTermSalesTarget__c
                        );
                        phase3AchievementRate = calculatePercentage(
                            phase3Actual,
                            report.ObjectiveManagement__r.ThirdTermSalesTarget__c
                        );
                        monthAchievementRate = calculatePercentage(monthActual, monthTarget);
                        lastYearSameMonthRate = calculatePercentage(
                            monthActual,
                            report.ObjectiveManagement__r.SameMonthLastYearTotalSales_F__c
                        );
                    }
                }
            }
        } catch (Exception ex) {
            this.hasError = true;
            BulkProcessLog__c processLog = new BulkProcessLog__c(
                ProcessSubject__c = '運送売上実績表PDF出力時エラー発生通知',
                ProcessDetails__c = ex.getMessage() + ' ' + ex.getStackTraceString(),
                ProcessStatus__c = 'Error',
                ProcessType__c = 'ShippingSalesReportOutputCtrl',
                ToEmailGroupAddresses__c = 'SystemGroup'
            );
            errorMessage = '処理中に予期しないエラーが発生しました。<br/>お手数ですが、システム管理者までご連絡をお願いいたします。';
            insert processLog;
        }
        return null;
    }

    private static Map<Integer, String> weekdayMap = new Map<Integer, String>{
        1 => '月曜日',
        2 => '火曜日',
        3 => '水曜日',
        4 => '木曜日',
        5 => '金曜日',
        6 => '土曜日',
        7 => '日曜日'
    };

    /**
     * 期を取得
     * @param 日付
     * @return 期のNo.
     */
    public static Integer getPhase(Date reportDate) {
        Integer day = reportDate.day();

        Date firstOfNextMonth = reportDate.addMonths(1).toStartOfMonth();
        Date lastOfCurrentMonth = firstOfNextMonth.addDays(-1);
        Integer daysInMonth = lastOfCurrentMonth.day();

        if (day >= 1 && day <= 10) {
            return 1;
        } else if (day >= 11 && day <= 20) {
            return 2;
        } else if (day >= 21 && day <= daysInMonth) {
            return 3;
        }

        return null;
    }

    /**
     * 実績を取得
     * 対象オブジェクト：運送売上日報
     * @param phaseNumber:〇期実績
     * @param year:対象年
     * @param month:対象月
     * @return 実績
     */

    public static Decimal getPhaseActual(Integer phaseNumber, Integer year, Integer month) {
        Date startDate;
        Date endDate;

        Date lastDayOfMonth = Date.newInstance(year, month, 1).toStartOfMonth().addMonths(1).addDays(-1);

        if (phaseNumber == 1) {
            startDate = Date.newInstance(year, month, 1);
            endDate = Date.newInstance(year, month, 10);
        } else if (phaseNumber == 2) {
            startDate = Date.newInstance(year, month, 11);
            endDate = Date.newInstance(year, month, 20);
        } else if (phaseNumber == 3) {
            startDate = Date.newInstance(year, month, 21);
            endDate = lastDayOfMonth;
        } else if (phaseNumber == 0) {
            startDate = Date.newInstance(year, month, 1);
            endDate = lastDayOfMonth;
        } else {
            return 0;
        }

        AggregateResult[] results = [
            SELECT SUM(TotalSales_F__c) TotalSales
            FROM ShippingSalesReport__c
            WHERE Date__c >= :startDate AND Date__c <= :endDate
        ];
        Decimal totalActual = (results.size() > 0 &&
            results[0].get('TotalSales') != null)
            ? (Decimal) results[0].get('TotalSales')
            : 0;
        return totalActual != null ? totalActual : 0;
    }

    //パーセント計算
    public static Decimal calculatePercentage(Decimal numerator, Decimal denominator) {
        if (denominator == null || denominator == 0) {
            return 0;
        }

        Decimal percentage = (numerator / denominator) * 100;

        return percentage.setScale(1, RoundingMode.HALF_UP);
    }

    @AuraEnabled
    public static String getPdfPreviewUrl(Id recordId) {
        try {
            PageReference pdfPage = Page.ShippingSalesReportOutput;
            pdfPage.getParameters().put('id', recordId);
            return pdfPage.getUrl();
        } catch (Exception ex) {
            BulkProcessLog__c processLog = new BulkProcessLog__c(
                ProcessSubject__c = '運送売上実績表PDF出力時エラー発生通知',
                ProcessDetails__c = ex.getMessage() + ' ' + ex.getStackTraceString(),
                ProcessStatus__c = 'Error',
                ProcessType__c = 'ShippingSalesReportOutputCtrl',
                ToEmailGroupAddresses__c = 'SystemGroup'
            );

            insert processLog;
            throw new AuraHandledException(
                '処理中に予期しないエラーが発生しました。<br/>お手数ですが、システム管理者までご連絡をお願いいたします。'
            );
        }
    }

    @AuraEnabled
    public static void uploadPdfToRecord(Id recordId, String pdfUrl) {
        try {
            PageReference pdfPage = Page.ShippingSalesReportOutput;
            pdfPage.getParameters().put('id', recordId);

            Blob pdfBlob;
            if (Test.isRunningTest()) {
                pdfBlob = Blob.valueOf('Dummy PDF Content');
            } else {
                pdfBlob = pdfPage.getContentAsPDF();
            }

            Date outputDay = Date.today();
            if (String.isNotBlank(recordId)) {
                List<ShippingSalesReport__c> report = [
                    SELECT Id, Date__c
                    FROM ShippingSalesReport__c
                    WHERE Id = :recordId
                    LIMIT 1
                ];
                if (!report.isEmpty()) {
                    outputDay = report[0].Date__c;
                }
            }
            String formattedDate = String.valueOf(outputDay).replace('-', '') + '_' + System.now().format('yyyyMMddHHmmss');
            String fileName = '日報売上実績表_' + formattedDate + '.pdf';

            ContentVersion cv = new ContentVersion();
            cv.Title = filename;
            cv.PathOnClient = filename;
            cv.VersionData = pdfBlob;
            cv.IsMajorVersion = true;
            insert cv;

            cv = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id];

            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.ContentDocumentId = cv.ContentDocumentId;
            cdl.LinkedEntityId = recordId;
            cdl.ShareType = 'V';
            cdl.Visibility = 'AllUsers';
            insert cdl;
        } catch (Exception ex) {
            BulkProcessLog__c processLog = new BulkProcessLog__c(
                ProcessSubject__c = '運送売上実績表PDF出力時エラー発生通知',
                ProcessDetails__c = ex.getMessage() + ' ' + ex.getStackTraceString(),
                ProcessStatus__c = 'Error',
                ProcessType__c = 'ShippingSalesReportOutputCtrl',
                ToEmailGroupAddresses__c = 'SystemGroup'
            );

            insert processLog;
            throw new AuraHandledException(
                '処理中に予期しないエラーが発生しました。<br/>お手数ですが、システム管理者までご連絡をお願いいたします。'
            );
        }
    }
}