force-app/main/default/objects/BulkProcessLog__c/BulkProcessLog__c.object-meta.xml
<CustomObject>
    <label>一括処理ログ</label>
    <nameField>
        <displayFormat>BPL-{0000000000}</displayFormat>
        <label>一括処理ログ#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BulkProcessLog__c/fields/ProcessLog__c.field-meta.xml
<CustomField>
    <fullName>ProcessLog__c</fullName>
    <label>処理ログ</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BulkProcessLog__c/fields/ProcessStatus__c.field-meta.xml
<CustomField>
    <fullName>ProcessStatus__c</fullName>
    <label>処理状態</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Start</fullName>
                <label>処理開始</label>
            </value>
            <value>
                <fullName>Processing</fullName>
                <label>処理中</label>
            </value>
            <value>
                <fullName>Success</fullName>
                <label>正常終了</label>
            </value>
            <value>
                <fullName>Error</fullName>
                <label>異常終了</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BulkProcessLog__c/fields/ProcessSubject__c.field-meta.xml
<CustomField>
    <fullName>ProcessSubject__c</fullName>
    <label>処理件名</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BulkProcessLog__c/fields/ProcessType__c.field-meta.xml
<CustomField>
    <fullName>ProcessType__c</fullName>
    <label>処理分類</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AutoGenWeeklyOffSchedule</fullName>
                <label>定休日勤務情報の自動生成</label>
            </value>
            <value>
                <fullName>UpsertScheduleByChangeWeeklyOff</fullName>
                <label>定休日変更時勤務情報変動</label>
            </value>
            <value>
                <fullName>CreateOrderFromRegularServiceBatch</fullName>
                <label>定期便注文作成バッチ</label>
            </value>
            <value>
                <fullName>RecordManualUpdate</fullName>
                <label>レコードの手動更新</label>
            </value>
            <value>
                <fullName>ImportFujiechoFareDetail</fullName>
                <label>富士エコー運賃明細インポート</label>
            </value>
            <value>
                <fullName>CreateShippingSalesReportBatch</fullName>
                <label>運賃売上日報作成バッチ</label>
            </value>
            <value>
                <fullName>StorageFeeAccountingDetailCreateBatch</fullName>
                <label>保管料の請求・支払明細作成のバッチ</label>
            </value>
            <value>
                <fullName>ImportTumixAttendance</fullName>
                <label>TUMIX出勤実績インポート</label>
            </value>
            <value>
                <fullName>OrderHeaderRelatedRecordsRollback</fullName>
                <label>注文の関連レコードのロールバック</label>
            </value>
            <value>
                <fullName>ShippingSalesReportOutputCtrl</fullName>
                <label>運送売上実績表PDF出力</label>
            </value>
            <value>
                <fullName>ShippedScheduleBatch</fullName>
            </value>
            <value>
                <fullName>ArrivedScheduleBatch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductStockInfo__c/ProductStockInfo__c.object-meta.xml
<CustomObject>
    <label>在庫情報</label>
    <nameField>
        <displayFormat>PSI-{00000000}</displayFormat>
        <label>在庫情報#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductStockInfo__c/fields/ArrivalDate__c.field-meta.xml
<CustomField>
    <fullName>ArrivalDate__c</fullName>
    <defaultValue>TODAY() -1</defaultValue>
    <inlineHelpText>入庫日のデフォルトが昨日になる</inlineHelpText>
    <label>入庫日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProductStockInfo__c/fields/ArrivalQuantity__c.field-meta.xml
<CustomField>
    <fullName>ArrivalQuantity__c</fullName>
    <label>数量（入庫）</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductStockInfo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>在庫状況</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PreRegistration</fullName>
                <label>仮登録</label>
            </value>
            <value>
                <fullName>Arrived</fullName>
                <label>入庫済み</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ArrivedScheduleBatch.cls
public with sharing class ArrivedScheduleBatch implements Database.Batchable<sObject>, Database.Stateful, Schedulable {
    // 実行日
    public Date executeDate = System.today();
    // 処理ログ
    private BulkProcessLog__c processLog = new BulkProcessLog__c();
    // 期制の開始日の一覧
    private List<Date> termCycleStartDateList = new List<Date>();
    // すべてのレコードの数量
    private Decimal allCount = 0;
    // 処理されたレコドの数量
    private Decimal processCount = 0;
    // 成功のレコードの数量
    private Decimal successCount = 0;
    // エラー一覧
    private List<String> errorList = new List<String>();
    // 処理時のエラーメッセージを変数で保存する
    private List<String> errorMessageList = new List<String>();

    public ArrivedScheduleBatch() {
    }
    public ArrivedScheduleBatch(Date executeDate) {
        this.executeDate = executeDate;
    }

    public void execute(SchedulableContext sc) {
        ArrivedScheduleBatch batch = new ArrivedScheduleBatch();
        Database.executeBatch(batch, 200);
    }

    public Database.Querylocator start(Database.BatchableContext bc) {
        // 処理ログを生成
        // 処理状態＝「処理開始」
        processLog.ProcessStatus__c = 'Start';
        // 処理件名
        processLog.ProcessSubject__c = '入庫済みに変更のバッチログ：' + executeDate;
        // 処理分類
        processLog.ProcessType__c = 'ArrivedScheduleBatch';

        // 在庫情報一覧を取得
        return Database.getQueryLocator(
            [
                SELECT Id, Status__c
                FROM ProductStockInfo__c
                WHERE
                    Status__c = NULL // 在庫条件＝NULL
                    AND ArrivalQuantity__c > 0 // 数量（入庫）＞０
                    AND ArrivalDate__c <= :executeDate // 入庫日 ＜＝ 現在の日
            ]
        );
    }

    public void execute(Database.BatchableContext bc, List<ProductStockInfo__c> psiList) {
        // 処理状態を更新
        processLog.ProcessStatus__c = 'Processing';
        // 一覧をチェック
        if (psiList == null || psiList.isEmpty())
            return;
        allCount += psiList.size();
        Savepoint sp = Database.setSavepoint();
        try {
            // 入庫済みに変更
            for (ProductStockInfo__c psi : psiList) {
                psi.Status__c = 'Arrived';
            }

            // 在庫情報を一つずつ更新
            for (ProductStockInfo__c psi : psiList) {
                List<ProductStockInfo__c> singleRecord = new List<ProductStockInfo__c>{ psi };
                Database.SaveResult[] saveResultList = Database.update(singleRecord, false);
                // 更新結果を確認
                for (Integer i = 0; i < saveResultList.size(); i++) {
                    Database.SaveResult ur = saveResultList[i];
                    if (false == ur.isSuccess()) {
                        // エラー集合
                        String errorMessage = singleRecord[i].Id + ' の在庫情報: \n';
                        for (Database.Error err : ur.getErrors()) {
                            errorMessage += err + '\n';
                        }
                        errorMessageList.add(errorMessage);
                    } else {
                        successCount++;
                    }
                }
                processCount += singleRecord.size();
            }
        } catch (Exception e) {
            System.debug('ArrivedScheduleBatch Error: ' + e.getMessage() + ': ' + e.getStackTraceString());
            errorList.add(e.getMessage() + ': ' + e.getStackTraceString());
            // データをロールバック
            Database.rollback(sp);
        }
    }

    // 処理完了、成功ログかエラーログを作成
    public void finish(Database.BatchableContext bc) {
        String log =
            'レコードの数量：' +
            allCount +
            '\n' +
            '処理されたレコードの数量：' +
            processCount +
            '\n成功の数量：' +
            successCount +
            '\n';
        String status = processLog.ProcessStatus__c;
        if (!errorList.isEmpty()) {
            for (String error : errorList) {
                System.debug('ERROR: ' + error);
                log += error + '\n';
            }
            status = 'Error';
        } else if (!errorMessageList.isEmpty()) {
            for (String error : errorMessageList) {
                System.debug('更新のERROR: ' + error);
                log += error + '\n';
            }
            status = 'Error';
        } else if (allCount > 0 && allCount == successCount) {
            status = 'Success';
        }
        processLog.ProcessStatus__c = status;
        processLog.ProcessLog__c = log;
        insert processLog;
    }
}