force-app/main/default/objects/BulkProcessLog__c/BulkProcessLog__c.object-meta.xml
<CustomObject>
    <label>一括処理ログ</label>
    <nameField>
        <displayFormat>BPL-{0000000000}</displayFormat>
        <label>一括処理ログ#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BulkProcessLog__c/fields/OrderHeader__c.field-meta.xml
<CustomField>
    <fullName>OrderHeader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>注文</label>
    <referenceTo>OrderHeader__c</referenceTo>
    <relationshipLabel>一括処理ログ</relationshipLabel>
    <relationshipName>BulkProcessLogList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DispatchDetail__c/DispatchDetail__c.object-meta.xml
<CustomObject>
    <label>配車明細</label>
    <nameField>
        <displayFormat>DED-{00000000}</displayFormat>
        <label>配車明細#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchDetail__c/fields/OrderHeader__c.field-meta.xml
<CustomField>
    <fullName>OrderHeader__c</fullName>
    <label>注文</label>
    <referenceTo>OrderHeader__c</referenceTo>
    <relationshipLabel>配車明細 (注文　主従)</relationshipLabel>
    <relationshipName>DispatchDetailList</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderHeader__c/OrderHeader__c.object-meta.xml
<CustomObject>
    <label>注文</label>
    <nameField>
        <label>注文#</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderHeader__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>荷主</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>注文 (荷主)</relationshipLabel>
    <relationshipName>OrderHeaderList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderHeader__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Raysheetに入力が必要な必須項目</description>
    <inlineHelpText>いずれかの条件と一致する必要があります。【荷主名※または請求先名】【マルエス(自社)】【荷主名が空のもの】</inlineHelpText>
    <label>着地</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
        <errorMessage>選択した着地はこの荷主の注文レコードでは使用できません。</errorMessage>
        <filterItems>
            <field>OriginDestination__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>OriginDestination__c.Account__r.AccountCode__c</field>
            <operation>equals</operation>
            <value>9901</value>
        </filterItems>
        <filterItems>
            <field>OriginDestination__c.Account__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>OriginDestination__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.InvoiceAccount__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OriginDestination__c</referenceTo>
    <relationshipLabel>注文 (着地)</relationshipLabel>
    <relationshipName>OrderHeaderDestinationList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderHeader__c/fields/InvoiceAccount__c.field-meta.xml
<CustomField>
    <fullName>InvoiceAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>請求先（集計使用名）</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>注文 (請求先（集計使用名）)</relationshipLabel>
    <relationshipName>OrderHeaderInvoiceAccountList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderHeader__c/fields/OriginPlace__c.field-meta.xml
<CustomField>
    <fullName>OriginPlace__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Raysheetに入力が必要な必須項目</description>
    <inlineHelpText>いずれかの条件と一致する必要があります。【荷主名※または請求先名】【マルエス(自社)】【荷主名が空のもの】</inlineHelpText>
    <label>発地</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
        <errorMessage>選択した発地はこの荷主の注文レコードでは使用できません。</errorMessage>
        <filterItems>
            <field>OriginDestination__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>OriginDestination__c.Account__r.AccountCode__c</field>
            <operation>equals</operation>
            <value>9901</value>
        </filterItems>
        <filterItems>
            <field>OriginDestination__c.Account__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>OriginDestination__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.InvoiceAccount__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OriginDestination__c</referenceTo>
    <relationshipLabel>注文（発地）</relationshipLabel>
    <relationshipName>OrderHeaderOriginPlaceList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderHeader__c/fields/ShippingFee__c.field-meta.xml
<CustomField>
    <fullName>ShippingFee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>運賃#</label>
    <referenceTo>ShippingFee__c</referenceTo>
    <relationshipLabel>注文</relationshipLabel>
    <relationshipName>OrderHeaderList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderHeader__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>「受付」→「受付確認済」の際は受注課担当がダブルチェックする</description>
    <label>状態</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reception</fullName>
                <default>true</default>
                <label>受付</label>
            </value>
            <value>
                <fullName>ReceptionCompleted</fullName>
                <label>受付確認済み</label>
            </value>
            <value>
                <fullName>DispatchCompleted</fullName>
                <label>配車完了</label>
            </value>
            <value>
                <fullName>DeliveryCompleted</fullName>
                <label>配送完了</label>
            </value>
            <value>
                <fullName>Cancel</fullName>
                <label>キャンセル</label>
            </value>
            <value>
                <fullName>InvoiceConfirmed</fullName>
                <label>請求処理済み</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OriginDestination__c/OriginDestination__c.object-meta.xml
<CustomObject>
    <label>発着地</label>
    <nameField>
        <label>発着地名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OriginDestination__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>荷主</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>発着地</relationshipLabel>
    <relationshipName>OriginDestinationList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PriceTable__c/PriceTable__c.object-meta.xml
<CustomObject>
    <label>価格管理</label>
    <nameField>
        <label>価格管理名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PriceTable__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>価格管理 (荷主)</relationshipLabel>
    <relationshipName>PriceTableList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PriceTable__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>状況</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>作成中</label>
            </value>
            <value>
                <fullName>Revising</fullName>
                <label>修正中</label>
            </value>
            <value>
                <fullName>PendingApproval</fullName>
                <label>承認待ち</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>承認</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>却下</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ShippingFee__c/ShippingFee__c.object-meta.xml
<CustomObject>
    <label>運賃</label>
    <nameField>
        <displayFormat>SHF-{00000000}</displayFormat>
        <label>運賃#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ShippingFee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>価格管理の荷主を設定</description>
    <label>荷主</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>ShippingFeeMasterAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ShippingFee__c/fields/ArrivalPrefecture__c.field-meta.xml
<CustomField>
    <fullName>ArrivalPrefecture__c</fullName>
    <label>都道府県（着地）</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>北海道</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>青森県</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>岩手県</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>宮城県</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>秋田県</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>山形県</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>福島県</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>茨城県</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>栃木県</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>群馬県</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>埼玉県</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>千葉県</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>東京都</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>神奈川県</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>新潟県</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>富山県</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>石川県</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>福井県</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>山梨県</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>長野県</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>岐阜県</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>静岡県</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>愛知県</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>三重県</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>滋賀県</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>京都府</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>大阪府</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>兵庫県</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>奈良県</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>和歌山県</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ShippingFee__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>着地</label>
    <referenceTo>OriginDestination__c</referenceTo>
    <relationshipName>ShippingFeeDestinationList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ShippingFee__c/fields/PriceTable__c.field-meta.xml
<CustomField>
    <fullName>PriceTable__c</fullName>
    <label>価格管理</label>
    <referenceTo>PriceTable__c</referenceTo>
    <relationshipName>ShippingFeeList</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ShippingFee__c/fields/ShippingFee__c.field-meta.xml
<CustomField>
    <fullName>ShippingFee__c</fullName>
    <label>運賃</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/DispatchDetailTriggerHandler_T.cls
@isTest
private class DispatchDetailTriggerHandler_T {
    @TestSetup
    static void makeData() {
        Account acc = TestDataFactory.createAccount('12345', false);
        insert acc;

        OriginDestination__c origin = TestDataFactory.createOriginDestination(acc.Id, false);
        origin.Name = 'Test origin';
        insert origin;
        OriginDestination__c destination = TestDataFactory.createOriginDestination(acc.Id, false);
        destination.Name = 'Test destination';
        insert destination;

        PriceTable__c priceTable = new PriceTable__c();
        priceTable.Name = 'Test';
        insert priceTable;

        ShippingFee__c shippingFee = new ShippingFee__c();
        shippingFee.PriceTable__c = priceTable.Id;
        shippingFee.ArrivalPrefecture__c = '13';
        insert shippingFee;

        OrderHeader__c order = new OrderHeader__c();
        order.Status__c = 'Reception';
        order.ShippingFee__c = shippingFee.Id;
        order.Account__c = acc.Id;
        order.OriginPlace__c = origin.Id;
        order.Destination__c = destination.Id;
        order.InvoiceAccount__c = acc.Id;
        order.UnitForShippingFeeCal__c = 'Case';
        insert order;

        DispatchDetail__c dispatchDetail = new DispatchDetail__c();
        dispatchDetail.OrderHeader__c = order.Id;
        insert dispatchDetail;
        update dispatchDetail;
    }
    @isTest
    public static void insertManualUpdateLogTest() {
        DispatchDetail__c dispatchDetail = [
            SELECT Id, ManualUpdateDatetime__c
            FROM DispatchDetail__c
            LIMIT 1
        ];

        Test.startTest();
        dispatchDetail.ManualUpdateNote__c = 'insertManualUpdateLogTest()による手動更新のデモ';
        update dispatchDetail;
        Test.stopTest();

        List<DispatchDetail__c> updatedDispatchDetails = [
            SELECT Id, ManualUpdateDatetime__c, ManualUpdateNote__c
            FROM DispatchDetail__c
            LIMIT 1
        ];

        List<BulkProcessLog__c> logs = [
            SELECT Id, ProcessType__c, ProcessDetails__c
            FROM BulkProcessLog__c
            WHERE ProcessType__c = 'RecordManualUpdate'
        ];

        System.debug('配車明細手動更新メモ' + updatedDispatchDetails[0].ManualUpdateNote__c);
        System.debug('ログ内容' + logs[0].ProcessDetails__c);
        Assert.areEqual(null, updatedDispatchDetails[0].ManualUpdateNote__c);
        Assert.areEqual('手動更新メモ: insertManualUpdateLogTest()による手動更新のデモ', logs[0].ProcessDetails__c);
    }
}