force-app/main/default/objects/InvoiceDocument__c/InvoiceDocument__c.object-meta.xml
<CustomObject>
    <label>請求書</label>
    <nameField>
        <label>請求書名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceDocument__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <label>請求日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InvoiceDocument__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>状態</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirm</fullName>
                <default>true</default>
                <label>確認中</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
                <label>処理済み</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoiceDocument__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>タイプ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>請求書</fullName>
                <default>true</default>
                <label>請求書</label>
            </value>
            <value>
                <fullName>支払書</fullName>
            </value>
            <value>
                <fullName>運送請求書</fullName>
            </value>
            <value>
                <fullName>保管・荷役明細書</fullName>
            </value>
            <value>
                <fullName>シャトレーゼの請求</fullName>
            </value>
            <value>
                <fullName>エレクターの請求</fullName>
            </value>
            <value>
                <fullName>出向者の請求</fullName>
            </value>
            <value>
                <fullName>恒温槽</fullName>
            </value>
            <value>
                <fullName>売上のマイナス明細</fullName>
            </value>
            <value>
                <fullName>諸掛データ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderDetail__c/OrderDetail__c.object-meta.xml
<CustomObject>
    <label>注文明細</label>
    <nameField>
        <label>注文明細#</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderDetail__c/fields/OrderHeader__c.field-meta.xml
<CustomField>
    <fullName>OrderHeader__c</fullName>
    <label>注文</label>
    <referenceTo>OrderHeader__c</referenceTo>
    <relationshipLabel>注文明細</relationshipLabel>
    <relationshipName>OrderDetailList</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderDetail__c/fields/ProductMaster__c.field-meta.xml
<CustomField>
    <fullName>ProductMaster__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>商品マスタ</label>
    <referenceTo>ProductMaster__c</referenceTo>
    <relationshipLabel>注文明細</relationshipLabel>
    <relationshipName>OrderDetailList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderHeader__c/OrderHeader__c.object-meta.xml
<CustomObject>
    <label>注文</label>
    <nameField>
        <label>注文#</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderHeader__c/fields/ShippingFee__c.field-meta.xml
<CustomField>
    <fullName>ShippingFee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>運賃#</label>
    <referenceTo>ShippingFee__c</referenceTo>
    <relationshipLabel>注文</relationshipLabel>
    <relationshipName>OrderHeaderList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderHeader__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>「受付」→「受付確認済」の際は受注課担当がダブルチェックする</description>
    <label>状態</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reception</fullName>
                <default>true</default>
                <label>受付</label>
            </value>
            <value>
                <fullName>ReceptionCompleted</fullName>
                <label>受付確認済み</label>
            </value>
            <value>
                <fullName>DispatchCompleted</fullName>
                <label>配車完了</label>
            </value>
            <value>
                <fullName>DeliveryCompleted</fullName>
                <label>配送完了</label>
            </value>
            <value>
                <fullName>Cancel</fullName>
                <label>キャンセル</label>
            </value>
            <value>
                <fullName>InvoiceConfirmed</fullName>
                <label>請求処理済み</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PickingList__c/PickingList__c.object-meta.xml
<CustomObject>
    <label>ピッキングリスト</label>
    <nameField>
        <displayFormat>PCL-{00000000}</displayFormat>
        <label>ピッキングリスト#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PickingList__c/fields/OrderDetail__c.field-meta.xml
<CustomField>
    <fullName>OrderDetail__c</fullName>
    <label>注文明細</label>
    <referenceTo>OrderDetail__c</referenceTo>
    <relationshipLabel>ピッキングリスト (注文明細)</relationshipLabel>
    <relationshipName>PickingList</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PickingList__c/fields/OrderHeader__c.field-meta.xml
<CustomField>
    <fullName>OrderHeader__c</fullName>
    <label>注文</label>
    <referenceTo>OrderHeader__c</referenceTo>
    <relationshipLabel>ピッキングリスト (注文)</relationshipLabel>
    <relationshipName>PickingList</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PickingList__c/fields/ProductMaster__c.field-meta.xml
<CustomField>
    <fullName>ProductMaster__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>商品マスタ</label>
    <referenceTo>ProductMaster__c</referenceTo>
    <relationshipLabel>ピッキングリスト</relationshipLabel>
    <relationshipName>PickingList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PickingList__c/fields/ProductStockInfo__c.field-meta.xml
<CustomField>
    <fullName>ProductStockInfo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Raysheetに入力が必要な必須項目</description>
    <label>在庫情報</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>商品名が一致していません。</errorMessage>
        <filterItems>
            <field>ProductStockInfo__c.ProductMaster__c</field>
            <operation>equals</operation>
            <valueField>$Source.ProductMaster__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ProductStockInfo__c</referenceTo>
    <relationshipLabel>ピッキングリスト</relationshipLabel>
    <relationshipName>PickingList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PriceTable__c/PriceTable__c.object-meta.xml
<CustomObject>
    <label>価格管理</label>
    <nameField>
        <label>価格管理名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PriceTable__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>状況</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>作成中</label>
            </value>
            <value>
                <fullName>Revising</fullName>
                <label>修正中</label>
            </value>
            <value>
                <fullName>PendingApproval</fullName>
                <label>承認待ち</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>承認</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>却下</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductMaster__c/ProductMaster__c.object-meta.xml
<CustomObject>
    <label>商品マスタ</label>
    <nameField>
        <label>商品名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductMaster__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>商品コード</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductMaster__c/fields/ProductManagementCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductManagementCategory__c</fullName>
    <label>商品管理区分</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <default>true</default>
                <label>4：ケース・バラ管理（荷崩し自動）</label>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
                <isActive>false</isActive>
                <label>2</label>
            </value>
            <value>
                <fullName>3</fullName>
                <isActive>false</isActive>
                <label>3</label>
            </value>
            <value>
                <fullName>5</fullName>
                <isActive>false</isActive>
                <label>5</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductMaster__c/fields/WarehouseMaster__c.field-meta.xml
<CustomField>
    <fullName>WarehouseMaster__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>値設定した場合、倉庫保管対象と見なす</description>
    <label>倉庫</label>
    <referenceTo>WarehouseMaster__c</referenceTo>
    <relationshipLabel>商品マスタ</relationshipLabel>
    <relationshipName>ProductMasterList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductStockInfo__c/ProductStockInfo__c.object-meta.xml
<CustomObject>
    <label>在庫情報</label>
    <nameField>
        <displayFormat>PSI-{00000000}</displayFormat>
        <label>在庫情報#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductStockInfo__c/fields/ProductMaster__c.field-meta.xml
<CustomField>
    <fullName>ProductMaster__c</fullName>
    <label>商品マスタ</label>
    <referenceTo>ProductMaster__c</referenceTo>
    <relationshipLabel>在庫情報</relationshipLabel>
    <relationshipName>ProductStockInfoList</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProductStockInfo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>在庫状況</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PreRegistration</fullName>
                <label>仮登録</label>
            </value>
            <value>
                <fullName>Arrived</fullName>
                <label>入庫済み</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductStockInfo__c/fields/WarehouseMaster__c.field-meta.xml
<CustomField>
    <fullName>WarehouseMaster__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>倉庫</label>
    <referenceTo>WarehouseMaster__c</referenceTo>
    <relationshipLabel>在庫情報</relationshipLabel>
    <relationshipName>ProductStockInfoList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ShippingFee__c/ShippingFee__c.object-meta.xml
<CustomObject>
    <label>運賃</label>
    <nameField>
        <displayFormat>SHF-{00000000}</displayFormat>
        <label>運賃#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ShippingFee__c/fields/PriceTable__c.field-meta.xml
<CustomField>
    <fullName>PriceTable__c</fullName>
    <label>価格管理</label>
    <referenceTo>PriceTable__c</referenceTo>
    <relationshipName>ShippingFeeList</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ShippingFee__c/fields/ShippingFee__c.field-meta.xml
<CustomField>
    <fullName>ShippingFee__c</fullName>
    <label>運賃</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/WarehouseMaster__c/WarehouseMaster__c.object-meta.xml
<CustomObject>
    <label>倉庫</label>
    <nameField>
        <label>倉庫名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WarehouseMaster__c/fields/WarehouseCode__c.field-meta.xml
<CustomField>
    <fullName>WarehouseCode__c</fullName>
    <label>倉庫コード</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PickingListTriggerHandler_T.cls
@isTest
private class PickingListTriggerHandler_T {
    @TestSetup
    static void makeData() {
        InvoiceDocument__c inv = new InvoiceDocument__c();
        inv.Type__c = '請求書';
        inv.Status__c = 'Confirm';
        inv.InvoiceDate__c = Date.newInstance(1900, 1, 1);
        insert inv;

        PriceTable__c priceTable = new PriceTable__c();
        priceTable.Name = 'Test';
        insert priceTable;

        ShippingFee__c shippingFee = new ShippingFee__c();
        shippingFee.PriceTable__c = priceTable.Id;
        insert shippingFee;

        OrderHeader__c order = new OrderHeader__c();
        order.Status__c = 'Reception';
        order.ShippingFee__c = shippingFee.Id;
        insert order;

        ProductMaster__c product = new ProductMaster__c();
        product.Name = 'TestProduct';
        product.ProductCode__c = 'Test';
        product.ProductManagementCategory__c = '4';
        insert product;

        OrderDetail__c orderDetail = new OrderDetail__c();
        orderDetail.OrderHeader__c = order.Id;
        orderDetail.ProductMaster__c = product.Id;
        orderDetail.Quantity__c = 5;
        insert orderDetail;

        WarehouseMaster__c wm = new WarehouseMaster__c();
        wm.Name = 'TestSouko';
        wm.WarehouseCode__c = 'Test';
        insert wm;

        ProductStockInfo__c psi = new ProductStockInfo__c();
        psi.WarehouseMaster__c = wm.Id;
        psi.ProductMaster__c = product.Id;
        psi.ArrivalQuantity__c = 20;
        psi.AllocatedQuantity__c = 0;
        psi.ShippedQuantity__c = 0;
        insert psi;

        ProductStockInfo__c psi2 = new ProductStockInfo__c();
        psi2.WarehouseMaster__c = wm.Id;
        psi2.ProductMaster__c = product.Id;
        psi2.ArrivalQuantity__c = 10;
        psi2.AllocatedQuantity__c = 0;
        psi2.ShippedQuantity__c = 0;
        insert psi2;

        PickingList__c pl = new PickingList__c();
        pl.ProductStockInfo__c = psi.Id;
        pl.Quantity__c = 5;
        pl.OrderHeader__c = order.Id;
        pl.OrderDetail__c = orderDetail.Id;
        insert pl;

        PickingList__c pl2 = new PickingList__c();
        pl2.ProductStockInfo__c = psi.Id;
        pl2.Quantity__c = 3;
        pl2.OrderHeader__c = order.Id;
        pl2.OrderDetail__c = orderDetail.Id;
        insert pl2;
    }

    // ピッキングリストを新規作成
    @isTest
    public static void productStockInfoRollupAllocatedQuantity_insertQuantityChangeToValue_stockInfoQuantityChange() {
        PickingList__c pl = [
            SELECT Id, ProductStockInfo__c, Quantity__c
            FROM PickingList__c
            ORDER BY CreatedDate ASC
            LIMIT 1
        ];

        ProductStockInfo__c psi = [
            SELECT Id, AllocatedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :pl.ProductStockInfo__c
            LIMIT 1
        ];
        Decimal priorAllocated = psi.AllocatedQuantity__c;

        OrderDetail__c orderDetail = [SELECT Id, OrderHeader__c FROM OrderDetail__c LIMIT 1];

        PickingList__c pl3 = new PickingList__c();
        pl3.ProductStockInfo__c = psi.Id;
        pl3.Quantity__c = 3;
        pl3.OrderHeader__c = orderDetail.OrderHeader__c;
        pl3.OrderDetail__c = orderDetail.Id;

        Test.startTest();
        insert pl3;
        Test.stopTest();

        psi = [
            SELECT Id, AllocatedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :psi.Id
            LIMIT 1
        ];

        Assert.areEqual(priorAllocated + 3, psi.AllocatedQuantity__c); // 前の値　＋　作成したピッキングリストの数量
    }

    // ピッキングリストの数量を更新
    @isTest
    public static void productStockInfoRollupAllocatedQuantity_updateQuantityChangeToValue_stockInfoQuantityChange() {
        PickingList__c pl = [
            SELECT Id, ProductStockInfo__c, Quantity__c
            FROM PickingList__c
            ORDER BY CreatedDate ASC
            LIMIT 1
        ];

        ProductStockInfo__c psi = [
            SELECT Id, AllocatedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :pl.ProductStockInfo__c
            LIMIT 1
        ];

        Decimal priorAllocated = psi.AllocatedQuantity__c;

        pl.Quantity__c = pl.Quantity__c + 3;

        Test.startTest();
        update pl;
        Test.stopTest();

        psi = [
            SELECT Id, AllocatedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :psi.Id
            LIMIT 1
        ];

        Assert.areEqual(priorAllocated + 3, psi.AllocatedQuantity__c); // 前の値　＋　更新の差分
    }

    // ピッキングリストの数量を空に更新
    @isTest
    public static void productStockInfoRollupAllocatedQuantity_updateQuantityChangeToNull_stockInfoQuantityChange() {
        PickingList__c pl = [
            SELECT Id, ProductStockInfo__c, Quantity__c
            FROM PickingList__c
            ORDER BY CreatedDate ASC
            LIMIT 1
        ];

        ProductStockInfo__c psi = [
            SELECT Id, AllocatedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :pl.ProductStockInfo__c
            LIMIT 1
        ];

        Decimal priorAllocated = psi.AllocatedQuantity__c;
        Decimal priorPLQuantity = pl.Quantity__c;
        pl.Quantity__c = null;

        Test.startTest();
        update pl;
        Test.stopTest();

        psi = [
            SELECT Id, AllocatedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :psi.Id
            LIMIT 1
        ];

        Assert.isTrue(priorAllocated != 0);
        Assert.areEqual(priorAllocated - priorPLQuantity, psi.AllocatedQuantity__c);
    }

    // ピッキングリストの在庫情報を空に更新
    @isTest
    public static void productStockInfoRollupAllocatedQuantity_updateStockInfoChangeToNull_stockInfoQuantityChange() {
        PickingList__c pl = [
            SELECT Id, ProductStockInfo__c, Quantity__c
            FROM PickingList__c
            ORDER BY CreatedDate ASC
            LIMIT 1
        ];

        ProductStockInfo__c psi = [
            SELECT Id, AllocatedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :pl.ProductStockInfo__c
            LIMIT 1
        ];

        Decimal priorAllocated = psi.AllocatedQuantity__c;
        Decimal priorPLQuantity = pl.Quantity__c;
        pl.ProductStockInfo__c = null;

        Test.startTest();
        update pl;
        Test.stopTest();

        psi = [
            SELECT Id, AllocatedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :psi.Id
            LIMIT 1
        ];

        Assert.isTrue(priorAllocated != 0);
        Assert.areEqual(priorAllocated - priorPLQuantity, psi.AllocatedQuantity__c);
    }

    // ピッキングリストを別の在庫情報に変更
    @isTest
    public static void productStockInfoRollupAllocatedQuantity_updateStockInfoChangeToValue_stockInfoQuantityChange() {
        PickingList__c pl = [
            SELECT Id, ProductStockInfo__c, Quantity__c
            FROM PickingList__c
            ORDER BY CreatedDate ASC
            LIMIT 1
        ];

        ProductStockInfo__c psi = [
            SELECT Id, AllocatedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :pl.ProductStockInfo__c
            LIMIT 1
        ];

        Decimal priorAllocated = psi.AllocatedQuantity__c;

        ProductStockInfo__c psi2 = [
            SELECT Id, AllocatedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id != :pl.ProductStockInfo__c
            LIMIT 1
        ];

        Decimal priorAllocated2 = psi2.AllocatedQuantity__c;

        pl.ProductStockInfo__c = psi2.Id;

        Test.startTest();
        update pl;
        Test.stopTest();

        psi = [
            SELECT Id, AllocatedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :psi.Id
            LIMIT 1
        ];

        psi2 = [
            SELECT Id, AllocatedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :psi2.Id
            LIMIT 1
        ];

        Assert.areEqual(priorAllocated - pl.Quantity__c, psi.AllocatedQuantity__c); // 前の在庫情報の引き当て済み数　ー　ピッキングリストの数量
        Assert.areEqual(priorAllocated2 + pl.Quantity__c, psi2.AllocatedQuantity__c); // 後の在庫情報の引き当て済み数を更新　＋　ピッキングリストの数量
    }

    // ピッキングリストを削除
    @isTest
    public static void productStockInfoRollupAllocatedQuantity_delete_stockInfoQuantityChange() {
        PickingList__c pl = [
            SELECT Id, ProductStockInfo__c, Quantity__c
            FROM PickingList__c
            ORDER BY CreatedDate ASC
            LIMIT 1
        ];

        ProductStockInfo__c psi = [
            SELECT Id, AllocatedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :pl.ProductStockInfo__c
            LIMIT 1
        ];
        Decimal priorAllocated = psi.AllocatedQuantity__c;

        Test.startTest();
        delete pl;
        Test.stopTest();

        psi = [
            SELECT Id, AllocatedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :pl.ProductStockInfo__c
            LIMIT 1
        ];

        Assert.areEqual(priorAllocated - pl.Quantity__c, psi.AllocatedQuantity__c); // 在庫情報の引き当て済み数　ー　削除したピッキングリストの数量
    }

    // ピッキングリストを削除して、削除取消
    @isTest
    public static void productStockInfoRollupAllocatedQuantity_undelete_stockInfoQuantityChange() {
        PickingList__c pl = [
            SELECT Id, ProductStockInfo__c, Quantity__c
            FROM PickingList__c
            ORDER BY CreatedDate ASC
            LIMIT 1
        ];

        ProductStockInfo__c psi = [
            SELECT Id, AllocatedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :pl.ProductStockInfo__c
            LIMIT 1
        ];
        Decimal priorAllocated = psi.AllocatedQuantity__c;

        delete pl;

        // 削除した後の情報
        psi = [
            SELECT Id, AllocatedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :pl.ProductStockInfo__c
            LIMIT 1
        ];
        Decimal afterDeleteAllocated = psi.AllocatedQuantity__c;

        Test.startTest();
        undelete pl;
        Test.stopTest();

        // 削除取り消した後の情報
        psi = [
            SELECT Id, AllocatedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :pl.ProductStockInfo__c
            LIMIT 1
        ];

        Assert.areEqual(priorAllocated - pl.Quantity__c, afterDeleteAllocated); // 削除した時、引き当て済み数の変更を確認
        Assert.areEqual(priorAllocated, psi.AllocatedQuantity__c); // 削除取消した後、元々の引き当て済み数に戻す
    }

    // すべてのピッキングリストを削除
    @isTest
    public static void productStockInfoRollupAllocatedQuantity_deleteAll_stockInfoQuantityChange() {
        List<PickingList__c> plList = [
            SELECT Id, ProductStockInfo__c, Quantity__c
            FROM PickingList__c
            ORDER BY CreatedDate ASC
        ];

        ProductStockInfo__c psi = [
            SELECT Id, AllocatedQuantity__c
            FROM ProductStockInfo__c
            ORDER BY CreatedDate ASC
            LIMIT 1
        ];

        Decimal priorAllocated = psi.AllocatedQuantity__c;

        Test.startTest();
        delete plList;
        Test.stopTest();

        psi = [
            SELECT Id, AllocatedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :psi.Id
            LIMIT 1
        ];

        Assert.areEqual(0, psi.AllocatedQuantity__c); // 出庫済み数を０になった
    }

    // 出庫済み数のテスト。ピッキングリストを新規作成
    @isTest
    public static void productStockInfoRollupShippedQuantity_insertQuantityChangeToValue_stockInfoShippedQuantityChange() {
        PickingList__c pl = [
            SELECT Id, ProductStockInfo__c, Quantity__c, Shipped__c
            FROM PickingList__c
            ORDER BY CreatedDate ASC
            LIMIT 1
        ];

        ProductStockInfo__c psi = [
            SELECT Id, ShippedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :pl.ProductStockInfo__c
            LIMIT 1
        ];
        Decimal priorShipped = psi.ShippedQuantity__c;
        if (priorShipped == null) {
            priorShipped = 0;
        }

        OrderDetail__c orderDetail = [SELECT Id, OrderHeader__c FROM OrderDetail__c LIMIT 1];

        PickingList__c pl3 = new PickingList__c();
        pl3.ProductStockInfo__c = psi.Id;
        pl3.Quantity__c = 3;
        pl3.OrderHeader__c = orderDetail.OrderHeader__c;
        pl3.OrderDetail__c = orderDetail.Id;
        pl3.Shipped__c = true;

        Test.startTest();
        insert pl3;
        Test.stopTest();

        psi = [
            SELECT Id, ShippedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :psi.Id
            LIMIT 1
        ];

        Assert.areEqual(priorShipped + 3, psi.ShippedQuantity__c); // 前の値　＋　作成したピッキングリストの数量
    }

    // 出庫済み数のテスト。ピッキングリストの数量を更新
    @isTest
    public static void productStockInfoRollupShippedQuantity_updateQuantityChangeToValue_stockInfoShippedQuantityChange() {
        PickingList__c pl = [
            SELECT Id, ProductStockInfo__c, Quantity__c, OrderDetail__c, OrderDetail__r.OrderHeader__c
            FROM PickingList__c
            ORDER BY CreatedDate ASC
            LIMIT 1
        ];

        PickingList__c pl3 = new PickingList__c();
        pl3.ProductStockInfo__c = pl.ProductStockInfo__c;
        pl3.Quantity__c = 3;
        pl3.OrderHeader__c = pl.OrderDetail__r.OrderHeader__c;
        pl3.OrderDetail__c = pl.OrderDetail__c;
        pl3.Shipped__c = true;
        insert pl3;

        ProductStockInfo__c psi = [
            SELECT Id, ShippedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :pl.ProductStockInfo__c
            LIMIT 1
        ];
        Assert.areEqual(pl3.Quantity__c, psi.ShippedQuantity__c);

        Decimal priorShipped = psi.ShippedQuantity__c;
        pl3.Quantity__c = priorShipped + 3;

        Test.startTest();
        update pl3;
        Test.stopTest();

        psi = [
            SELECT Id, ShippedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :psi.Id
            LIMIT 1
        ];

        Assert.areEqual(priorShipped + 3, psi.ShippedQuantity__c); // 前の値　＋　更新の差分
    }

    // 出庫済み数のテスト。ピッキングリストを別の在庫情報に変更
    @isTest
    public static void productStockInfoRollupShippedQuantity_updateStockInfoChangeToValue_stockInfoQuantityChange() {
        PickingList__c pl = [
            SELECT Id, ProductStockInfo__c, Quantity__c, OrderDetail__c, OrderDetail__r.OrderHeader__c
            FROM PickingList__c
            ORDER BY CreatedDate ASC
            LIMIT 1
        ];
        pl.Shipped__c = true;
        update pl;

        ProductStockInfo__c psi = [
            SELECT Id, ShippedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :pl.ProductStockInfo__c
            LIMIT 1
        ];
        Assert.areEqual(pl.Quantity__c, psi.ShippedQuantity__c);

        Decimal priorShipped = psi.ShippedQuantity__c;

        ProductStockInfo__c psi2 = [
            SELECT Id, ShippedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id != :pl.ProductStockInfo__c
            LIMIT 1
        ];

        Decimal priorShipped2 = psi2.ShippedQuantity__c;

        pl.ProductStockInfo__c = psi2.Id;

        Test.startTest();
        update pl;
        Test.stopTest();

        psi = [
            SELECT Id, ShippedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :psi.Id
            LIMIT 1
        ];

        psi2 = [
            SELECT Id, ShippedQuantity__c
            FROM ProductStockInfo__c
            WHERE Id = :psi2.Id
            LIMIT 1
        ];

        Assert.areEqual(priorShipped - pl.Quantity__c, psi.ShippedQuantity__c); // 前の在庫情報の出庫済み数　ー　ピッキングリストの数量
        Assert.areEqual(priorShipped2 + pl.Quantity__c, psi2.ShippedQuantity__c); // 後の在庫情報の出庫済み数を更新　＋　ピッキングリストの数量
    }
}