force-app/main/default/objects/ObjectiveManagement__c/ObjectiveManagement__c.object-meta.xml
<CustomObject>
    <label>目標管理</label>
    <nameField>
        <label>目標管理名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjectiveManagement__c/fields/FirstTermSalesTarget__c.field-meta.xml
<CustomField>
    <fullName>FirstTermSalesTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>第1期目標</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ObjectiveManagement__c/fields/ObjectiveManagement__c.field-meta.xml
<CustomField>
    <fullName>ObjectiveManagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>目標管理</label>
    <referenceTo>ObjectiveManagement__c</referenceTo>
    <relationshipLabel>目標管理</relationshipLabel>
    <relationshipName>ObjectiveManagementList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ObjectiveManagement__c/fields/SameMonthLastYearTotalSales__c.field-meta.xml
<CustomField>
    <fullName>SameMonthLastYearTotalSales__c</fullName>
    <label>前年同月実績（移行）</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ObjectiveManagement__c/fields/SameMonthLastYearTotalSubcontractorSales__c.field-meta.xml
<CustomField>
    <fullName>SameMonthLastYearTotalSubcontractorSales__c</fullName>
    <label>前年同月実績下払い（移行）</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ObjectiveManagement__c/fields/SecondTermSalesTarget__c.field-meta.xml
<CustomField>
    <fullName>SecondTermSalesTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>第2期目標</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ObjectiveManagement__c/fields/TargetMonth__c.field-meta.xml
<CustomField>
    <fullName>TargetMonth__c</fullName>
    <label>対象月</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ObjectiveManagement__c/fields/ThirdTermSalesTarget__c.field-meta.xml
<CustomField>
    <fullName>ThirdTermSalesTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>第3期目標</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/ShippingSalesReport__c.object-meta.xml
<CustomObject>
    <label>運送売上実績表</label>
    <nameField>
        <displayFormat>DSS-{0000000000}</displayFormat>
        <label>運送売上実績表#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ShippingSalesReport__c/fields/CharteredVehicleSales__c.field-meta.xml
<CustomField>
    <fullName>CharteredVehicleSales__c</fullName>
    <label>傭車全体（シャト除く）実績</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/CharteredVehicleSubcontractorSales__c.field-meta.xml
<CustomField>
    <fullName>CharteredVehicleSubcontractorSales__c</fullName>
    <label>傭車全体（シャト除く）下払い</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/ChateraiseSales__c.field-meta.xml
<CustomField>
    <fullName>ChateraiseSales__c</fullName>
    <label>シャトレーゼ実績</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/ChateraiseSubcontractorSales__c.field-meta.xml
<CustomField>
    <fullName>ChateraiseSubcontractorSales__c</fullName>
    <label>シャトレーゼ下払い</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>日付マスタ</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/FujiEchoCharteredVehicleSales__c.field-meta.xml
<CustomField>
    <fullName>FujiEchoCharteredVehicleSales__c</fullName>
    <label>富士エコー・ローソン（傭車）実績</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/FujiEchoCharteredVehicleSubcontractSales__c.field-meta.xml
<CustomField>
    <fullName>FujiEchoCharteredVehicleSubcontractSales__c</fullName>
    <label>富士エコー・ローソン（傭車）下払い</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/FujiEchoMfjVehicleSales__c.field-meta.xml
<CustomField>
    <fullName>FujiEchoMfjVehicleSales__c</fullName>
    <label>富士エコー・ローソン（MFJ車）実績</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/MARUSMfjVehicleSales__c.field-meta.xml
<CustomField>
    <fullName>MARUSMfjVehicleSales__c</fullName>
    <label>マルエス（MFJ車）実績</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/ObjectiveManagement__c.field-meta.xml
<CustomField>
    <fullName>ObjectiveManagement__c</fullName>
    <label>目標管理</label>
    <referenceTo>ObjectiveManagement__c</referenceTo>
    <relationshipName>ShippingSalesReport</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ShippingSalesReportOutputCtrl_T.cls
@isTest
private class ShippingSalesReportOutputCtrl_T {
    @TestSetup
    static void createData() {
        ObjectiveManagement__c objectiveManagement = new ObjectiveManagement__c();
        objectiveManagement.Name = 'test';
        objectiveManagement.TargetMonth__c = Date.today().toStartOfMonth();
        objectiveManagement.FirstTermSalesTarget__c = 100000;
        objectiveManagement.SecondTermSalesTarget__c = 200000;
        objectiveManagement.ThirdTermSalesTarget__c = 300000;
        objectiveManagement.SameMonthLastYearTotalSales__c = 200000;
        objectiveManagement.SameMonthLastYearTotalSubcontractorSales__c = 100000;

        insert objectiveManagement;

        ShippingSalesReport__c report = new ShippingSalesReport__c();
        report.Date__c = Date.today();
        report.MARUSMfjVehicleSales__c = 300000;
        report.ChateraiseSales__c = 100000;
        report.FujiEchoMfjVehicleSales__c = 100000;
        report.CharteredVehicleSales__c = 100000;
        report.FujiEchoCharteredVehicleSales__c = 50000;
        report.ChateraiseSubcontractorSales__c = 50000;
        report.CharteredVehicleSubcontractorSales__c = 100000;
        report.FujiEchoCharteredVehicleSubcontractSales__c = 50000;
        report.ObjectiveManagement__c = objectiveManagement.Id;

        insert report;
    }

    @isTest
    static void testMethod1() {
        Test.startTest();

        ShippingSalesReport__c report = [SELECT Id FROM ShippingSalesReport__c WHERE Date__c = :Date.today() LIMIT 1];

        PageReference pageRef = Page.ShippingSalesReportOutput;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id', report.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(new ShippingSalesReport__c());

        ShippingSalesReportOutputCtrl controller = new ShippingSalesReportOutputCtrl(sc);
        controller.Init();
        String pdfUrl = ShippingSalesReportOutputCtrl.getPdfPreviewUrl(report.Id);
        ShippingSalesReportOutputCtrl.uploadPdfToRecord(report.Id, pdfUrl);

        Test.stopTest();
    }

    @isTest
    static void testMethod2() {
        Test.startTest();

        ObjectiveManagement__c objectiveManagement = [
            SELECT Id, FirstTermSalesTarget__c
            FROM ObjectiveManagement__c
            WHERE TargetMonth__c = :Date.today().toStartOfMonth()
            LIMIT 1
        ];
        objectiveManagement.FirstTermSalesTarget__c = null;
        update objectiveManagement;

        ShippingSalesReport__c report = [SELECT Id FROM ShippingSalesReport__c WHERE Date__c = :Date.today() LIMIT 1];

        PageReference pageRef = Page.ShippingSalesReportOutput;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id', report.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(new ShippingSalesReport__c());

        ShippingSalesReportOutputCtrl controller = new ShippingSalesReportOutputCtrl(sc);
        controller.Init();
        String pdfUrl = ShippingSalesReportOutputCtrl.getPdfPreviewUrl(report.Id);
        ShippingSalesReportOutputCtrl.uploadPdfToRecord(report.Id, pdfUrl);

        Test.stopTest();
    }
}