force-app/main/default/objects/Account/fields/AccountCode__c.field-meta.xml
<CustomField>
    <fullName>AccountCode__c</fullName>
    <displayFormat>{0000}</displayFormat>
    <label>取引先コード</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/AccountingDetail__c/AccountingDetail__c.object-meta.xml
<CustomObject>
    <label>請求・支払明細</label>
    <nameField>
        <displayFormat>ACD-{00000000}</displayFormat>
        <label>請求・支払明細#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountingDetail__c/fields/AccountingType__c.field-meta.xml
<CustomField>
    <fullName>AccountingType__c</fullName>
    <label>収支区分</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>収入</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>支出</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountingDetail__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>金額</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AccountingDetail__c/fields/InvoiceAccount__c.field-meta.xml
<CustomField>
    <fullName>InvoiceAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>AccountingDetailInvoiceAccountList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountingDetail__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>項目</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>TargetDepartment__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>AccountingDetailItem</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountingDetail__c/fields/OrderHeader__c.field-meta.xml
<CustomField>
    <fullName>OrderHeader__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>注文</label>
    <referenceTo>OrderHeader__c</referenceTo>
    <relationshipName>AccountingDetailList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BulkProcessLog__c/BulkProcessLog__c.object-meta.xml
<CustomObject>
    <label>一括処理ログ</label>
    <nameField>
        <displayFormat>BPL-{0000000000}</displayFormat>
        <label>一括処理ログ#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BulkProcessLog__c/fields/OrderHeader__c.field-meta.xml
<CustomField>
    <fullName>OrderHeader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>注文</label>
    <referenceTo>OrderHeader__c</referenceTo>
    <relationshipLabel>一括処理ログ</relationshipLabel>
    <relationshipName>BulkProcessLogList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BulkProcessLog__c/fields/ProcessDetails__c.field-meta.xml
<CustomField>
    <fullName>ProcessDetails__c</fullName>
    <label>処理内容</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BulkProcessLog__c/fields/ProcessLog__c.field-meta.xml
<CustomField>
    <fullName>ProcessLog__c</fullName>
    <label>処理ログ</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BulkProcessLog__c/fields/ProcessStatus__c.field-meta.xml
<CustomField>
    <fullName>ProcessStatus__c</fullName>
    <label>処理状態</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Start</fullName>
                <label>処理開始</label>
            </value>
            <value>
                <fullName>Processing</fullName>
                <label>処理中</label>
            </value>
            <value>
                <fullName>Success</fullName>
                <label>正常終了</label>
            </value>
            <value>
                <fullName>Error</fullName>
                <label>異常終了</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BulkProcessLog__c/fields/ProcessSubject__c.field-meta.xml
<CustomField>
    <fullName>ProcessSubject__c</fullName>
    <label>処理件名</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BulkProcessLog__c/fields/ProcessType__c.field-meta.xml
<CustomField>
    <fullName>ProcessType__c</fullName>
    <label>処理分類</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AutoGenWeeklyOffSchedule</fullName>
                <label>定休日勤務情報の自動生成</label>
            </value>
            <value>
                <fullName>UpsertScheduleByChangeWeeklyOff</fullName>
                <label>定休日変更時勤務情報変動</label>
            </value>
            <value>
                <fullName>CreateOrderFromRegularServiceBatch</fullName>
                <label>定期便注文作成バッチ</label>
            </value>
            <value>
                <fullName>RecordManualUpdate</fullName>
                <label>レコードの手動更新</label>
            </value>
            <value>
                <fullName>ImportFujiechoFareDetail</fullName>
                <label>富士エコー運賃明細インポート</label>
            </value>
            <value>
                <fullName>CreateShippingSalesReportBatch</fullName>
                <label>運賃売上日報作成バッチ</label>
            </value>
            <value>
                <fullName>StorageFeeAccountingDetailCreateBatch</fullName>
                <label>保管料の請求・支払明細作成のバッチ</label>
            </value>
            <value>
                <fullName>ImportTumixAttendance</fullName>
                <label>TUMIX出勤実績インポート</label>
            </value>
            <value>
                <fullName>OrderHeaderRelatedRecordsRollback</fullName>
                <label>注文の関連レコードのロールバック</label>
            </value>
            <value>
                <fullName>ShippingSalesReportOutputCtrl</fullName>
                <label>運送売上実績表PDF出力</label>
            </value>
            <value>
                <fullName>ShippedScheduleBatch</fullName>
            </value>
            <value>
                <fullName>ArrivedScheduleBatch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BulkProcessLog__c/fields/ToEmailGroupAddresses__c.field-meta.xml
<CustomField>
    <fullName>ToEmailGroupAddresses__c</fullName>
    <label>送信先の課</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OrderGroup</fullName>
                <label>受注課</label>
            </value>
            <value>
                <fullName>DispatchGroup</fullName>
                <label>配車課</label>
            </value>
            <value>
                <fullName>SystemGroup</fullName>
                <label>システム課</label>
            </value>
            <value>
                <fullName>AccountingGroup</fullName>
                <label>経理課</label>
            </value>
            <value>
                <fullName>WarehouseGroup</fullName>
                <label>倉庫課</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MFJSetting__mdt/MFJSetting__mdt.object-meta.xml
<CustomObject>
    <label>マルエス環境変数</label>
</CustomObject>

force-app/main/default/objects/MFJSetting__mdt/fields/Value2__c.field-meta.xml
<CustomField>
    <fullName>Value2__c</fullName>
    <label>値2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MFJSetting__mdt/fields/Value3__c.field-meta.xml
<CustomField>
    <fullName>Value3__c</fullName>
    <label>値3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MFJSetting__mdt/fields/Value4__c.field-meta.xml
<CustomField>
    <fullName>Value4__c</fullName>
    <label>値4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MFJSetting__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <inlineHelpText>フラグの場合 True/False を入力してください</inlineHelpText>
    <label>値</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ObjectiveManagement__c/ObjectiveManagement__c.object-meta.xml
<CustomObject>
    <label>目標管理</label>
    <nameField>
        <label>目標管理名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjectiveManagement__c/fields/ObjectiveManagement__c.field-meta.xml
<CustomField>
    <fullName>ObjectiveManagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>目標管理</label>
    <referenceTo>ObjectiveManagement__c</referenceTo>
    <relationshipLabel>目標管理</relationshipLabel>
    <relationshipName>ObjectiveManagementList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ObjectiveManagement__c/fields/TargetMonth__c.field-meta.xml
<CustomField>
    <fullName>TargetMonth__c</fullName>
    <label>対象月</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderHeader__c/OrderHeader__c.object-meta.xml
<CustomObject>
    <label>注文</label>
    <nameField>
        <label>注文#</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderHeader__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>運賃</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderHeader__c/fields/InvoiceAccount__c.field-meta.xml
<CustomField>
    <fullName>InvoiceAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>請求先（集計使用名）</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>注文 (請求先（集計使用名）)</relationshipLabel>
    <relationshipName>OrderHeaderInvoiceAccountList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderHeader__c/fields/SubcontractFee__c.field-meta.xml
<CustomField>
    <fullName>SubcontractFee__c</fullName>
    <label>下請け運賃</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/ShippingSalesReport__c.object-meta.xml
<CustomObject>
    <label>運送売上実績表</label>
    <nameField>
        <displayFormat>DSS-{0000000000}</displayFormat>
        <label>運送売上実績表#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ShippingSalesReport__c/fields/CharteredVehicleSales__c.field-meta.xml
<CustomField>
    <fullName>CharteredVehicleSales__c</fullName>
    <label>傭車全体（シャト除く）実績</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/CharteredVehicleSubcontractorSales__c.field-meta.xml
<CustomField>
    <fullName>CharteredVehicleSubcontractorSales__c</fullName>
    <label>傭車全体（シャト除く）下払い</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/ChateraiseSales__c.field-meta.xml
<CustomField>
    <fullName>ChateraiseSales__c</fullName>
    <label>シャトレーゼ実績</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/ChateraiseSubcontractorSales__c.field-meta.xml
<CustomField>
    <fullName>ChateraiseSubcontractorSales__c</fullName>
    <label>シャトレーゼ下払い</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>日付マスタ</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/FujiEchoCharteredVehicleSales__c.field-meta.xml
<CustomField>
    <fullName>FujiEchoCharteredVehicleSales__c</fullName>
    <label>富士エコー・ローソン（傭車）実績</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/FujiEchoCharteredVehicleSubcontractSales__c.field-meta.xml
<CustomField>
    <fullName>FujiEchoCharteredVehicleSubcontractSales__c</fullName>
    <label>富士エコー・ローソン（傭車）下払い</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/FujiEchoMfjVehicleSales__c.field-meta.xml
<CustomField>
    <fullName>FujiEchoMfjVehicleSales__c</fullName>
    <label>富士エコー・ローソン（MFJ車）実績</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/MARUSMfjVehicleSales__c.field-meta.xml
<CustomField>
    <fullName>MARUSMfjVehicleSales__c</fullName>
    <label>マルエス（MFJ車）実績</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ShippingSalesReport__c/fields/ObjectiveManagement__c.field-meta.xml
<CustomField>
    <fullName>ObjectiveManagement__c</fullName>
    <label>目標管理</label>
    <referenceTo>ObjectiveManagement__c</referenceTo>
    <relationshipName>ShippingSalesReport</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/AccountingDetailItem.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>運賃</fullName>
    </customValue>
    <customValue>
        <fullName>付帯作業</fullName>
    </customValue>
    <customValue>
        <fullName>待機料</fullName>
    </customValue>
    <customValue>
        <fullName>燃料サーチャージ</fullName>
    </customValue>
    <customValue>
        <fullName>通行料</fullName>
    </customValue>
    <customValue>
        <fullName>貨物保険料</fullName>
    </customValue>
    <customValue>
        <fullName>シャトレーゼの請求</fullName>
    </customValue>
    <customValue>
        <fullName>キャンセル料</fullName>
    </customValue>
    <customValue>
        <fullName>保管料</fullName>
    </customValue>
    <customValue>
        <fullName>入庫料</fullName>
    </customValue>
    <customValue>
        <fullName>出庫料</fullName>
    </customValue>
    <customValue>
        <fullName>エレクターの請求</fullName>
    </customValue>
    <customValue>
        <fullName>出向者の請求</fullName>
    </customValue>
    <customValue>
        <fullName>恒温槽</fullName>
    </customValue>
    <customValue>
        <fullName>売上のマイナス明細</fullName>
    </customValue>
    <customValue>
        <fullName>諸掛データ</fullName>
    </customValue>
    <customValue>
        <fullName>下請け運賃</fullName>
    </customValue>
    <masterLabel>仕分明細項目</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CreateShippingSalesReportBatch.cls
/**
 * 請求・支払明細から運送売上実績表を作成バッチ
 * 起動時間：毎日
 */
public with sharing class CreateShippingSalesReportBatch implements Database.Batchable<Date>, Database.Stateful, Schedulable {
    public List<String> ItemSelectList = new List<String>{
        '運賃',
        '付帯作業',
        '待機料',
        '燃料サーチャージ',
        'シャトレーゼの請求',
        'キャンセル料',
        '下請け運賃'
    };
    public final String MetaDataDeveloperName = 'CreateShippingSalesReportParameter'; //メタデータDeveloperName
    public List<String> errorMessageList = new List<String>(); // 変数で処理時のエラーメッセージを保存する
    public Integer allCount = 0; // 処理件数
    public Integer sucessCount = 0; //処理成功件数
    public Integer errorCount = 0; //処理失敗件数
    String ChateraiseAccountCode; //シャトレーゼの取引先コード
    String FujiEchoAccountCode; //富士エコーの取引先コード
    Date StartDateMonthFirstDay; //開始日の月初日
    Date EndDateMonthLastDay; //終了日の月末日

    public List<String> errorNaiyouList = new List<String>(); // 処理時のエラーメッセージを保存する。
    BulkProcessLog__c processLog = new BulkProcessLog__c(); // ログ
    public static final String BATCH_JOB_PROCESS_TYPE = 'CreateShippingSalesReportBatch'; // バッチジョブ処理分類

    //スケジュール起動、バッチサイズ：１
    public void execute(SchedulableContext sc) {
        CreateShippingSalesReportBatch batch = new CreateShippingSalesReportBatch();
        Database.executeBatch(batch, 1);
    }

    public Iterable<Date> start(Database.BatchableContext BC) {
        // バッチ処理ログ
        String log = BATCH_JOB_PROCESS_TYPE + ',' + ' Date={' + System.Today() + '}, {' + datetime.now() + '}';
        // 処理内容
        String details = '運送売上実績表作成バッチ実行開始' + datetime.now();
        String subject = System.Today().format().replace('/', '') + ': 運送売上実績表作成バッチ実行開始';
        processLog = logBatchStatus(log, subject, details, 'Start', '');
        insert processLog;

        List<Date> DateList = new List<Date>();
        MFJSetting__mdt metadate = MFJSetting__mdt.getInstance(MetaDataDeveloperName);
        if (metadate == null) {
            return DateList;
        }
        Integer PastDays = metadate.Value__c == null ? 0 : Integer.valueOf(metadate.Value__c); ////過去日数
        Integer FutureDays = metadate.Value2__c == null ? 0 : Integer.valueOf(metadate.Value2__c); //未来日数
        ChateraiseAccountCode = String.valueOf(metadate.Value3__c); //シャトレーゼの取引先コード
        FujiEchoAccountCode = String.valueOf(metadate.Value4__c); //富士エコーの取引先コード
        Date StartDate = Date.today().addDays(-PastDays); //開始日
        Date EndDate = Date.today().addDays(FutureDays); //終了日
        StartDateMonthFirstDay = Date.newInstance(StartDate.year(), StartDate.month(), 1); //開始日の月初日
        EndDateMonthLastDay = Date.newInstance(EndDate.year(), EndDate.month(), 1).addMonths(1).addDays(-1); //終了日の月末日

        Date currentDate = StartDate;
        while (currentDate <= EndDate) {
            DateList.add(currentDate);
            currentDate = currentDate.addDays(1);
        }
        return DateList;
    }

    public void execute(Database.BatchableContext BC, List<Date> scope) {
        if (scope.isEmpty()) {
            return;
        }

        //請求・支払明細レコードを取得
        List<AccountingDetail__c> AccDetailList = [
            SELECT
                Id,
                Date__c, //日付
                Amount__c, //金額
                OrderHeader__c, //注文
                //OrderHeader__r.Amount__c, //注文.運賃
                OrderHeader__r.SubcontractFee__c, //注文.下請け運賃
                Item__c, //項目
                AccountingType__c, //収支区分 1:収入;2:支出
                InvoiceAccount__c, //取引先Id
                InvoiceAccount__r.AccountCode__c, //取引先.取引先コード
                InvoiceAccount__r.ParentId, //取引先.親取引先Id
                InvoiceAccount__r.Parent.AccountCode__c //取引先.親取引先.取引先コード
            FROM AccountingDetail__c
            WHERE
                Date__c IN :scope
                //AND  OrderHeader__c <> NUll
                AND Item__c IN :ItemSelectList
        ];
        //運送売上実績表レコードを取得
        List<ShippingSalesReport__c> shippingSalesReportList = [
            SELECT
                Id,
                Date__c, //日付
                MARUSMfjVehicleSales__c, //マルエス（MFJ車）実績
                ChateraiseSales__c, //シャトレーゼ実績
                FujiEchoMfjVehicleSales__c, //富士エコー・ローソン（MFJ車）実績
                CharteredVehicleSales__c, //傭車全体（シャト除く）実績
                FujiEchoCharteredVehicleSales__c, //富士エコー・ローソン（傭車）実績
                ChateraiseSubcontractorSales__c, //シャトレーゼ下払い
                CharteredVehicleSubcontractorSales__c, //傭車全体（シャト除く）下払い
                FujiEchoCharteredVehicleSubcontractSales__c, //富士エコー・ローソン（傭車）下払い
                ObjectiveManagement__c //目標管理Id
            FROM ShippingSalesReport__c
            WHERE Date__c IN :scope
        ];
        //目標管理レコードを取得
        List<ObjectiveManagement__c> objectiveManagementList = [
            SELECT Id, TargetMonth__c //対象月
            FROM ObjectiveManagement__c
            WHERE TargetMonth__c >= :StartDateMonthFirstDay AND TargetMonth__c <= :EndDateMonthLastDay
        ];

        Map<Date, List<AccountingDetail__c>> AccDetailMap = new Map<Date, List<AccountingDetail__c>>(); //Map<日付,請求・支払明細リスト>
        Map<Date, ShippingSalesReport__c> ShippingSalesReportMap = new Map<Date, ShippingSalesReport__c>(); //Map<日付,運送売上実績表>
        Map<Integer, Id> ObjectiveManagementMap = new Map<Integer, Id>(); //Map<月,目標管理Id>
        //Map<日付,請求・支払明細リスト>を作成
        for (AccountingDetail__c accDetail : AccDetailList) {
            if (accDetail.Date__c != null) {
                if (!AccDetailMap.containsKey(accDetail.Date__c)) {
                    List<AccountingDetail__c> accDetailSubList = new List<AccountingDetail__c>();
                    accDetailSubList.add(accDetail);
                    AccDetailMap.put(accDetail.Date__c, accDetailSubList);
                } else {
                    List<AccountingDetail__c> accDetailSubList = AccDetailMap.get(accDetail.Date__c);
                    accDetailSubList.add(accDetail);
                }
            }
        }
        //Map<日付,運送売上実績表>を作成
        for (ShippingSalesReport__c shippingSalesReport : shippingSalesReportList) {
            if (shippingSalesReport.Date__c != null) {
                ShippingSalesReportMap.put(shippingSalesReport.Date__c, shippingSalesReport);
            }
        }
        //Map<月,目標管理Id>を作成
        for (ObjectiveManagement__c objectiveManagement : objectiveManagementList) {
            if (objectiveManagement.TargetMonth__c != null) {
                Integer targetMonth = objectiveManagement.TargetMonth__c.month();
                ObjectiveManagementMap.put(targetMonth, objectiveManagement.Id);
            }
        }

        //日別で運送売上実績表を計算する
        for (Date keyDate : AccDetailMap.keySet()) {
            List<AccountingDetail__c> accountingDetails = AccDetailMap.get(keyDate);

            //注文NULLの場合、下請け運賃なし
            Decimal MARUSMfjVehicleSales = 0; //マルエス（MFJ車）実績　⇒　シャトレーゼ除くの注文 且つ 下請け運賃 = nullの運賃
            Decimal ChateraiseSales = 0; //シャトレーゼ実績　⇒　シャトレーゼの注文の運賃
            Decimal FujiEchoMfjVehicleSales = 0; //富士エコー・ローソン（MFJ車）実績　⇒　富士エコーの注文 且つ 下請け運賃 = nullの運賃
            Decimal CharteredVehicleSales = 0; //傭車全体（シャト除く）実績　⇒　シャトレーゼ除くの注文 且つ 下請け運賃 <> nullの運賃
            Decimal FujiEchoCharteredVehicleSales = 0; //富士エコー・ローソン（傭車）実績　⇒　富士エコーの注文 且つ 下請け運賃 <> nullの運賃

            Decimal ChateraiseSubcontractorSales = 0; //シャトレーゼ下払い　⇒　シャトレーゼの注文の下請け運賃
            Decimal CharteredVehicleSubcontractorSales = 0; //傭車全体（シャト除く）下払い　⇒　シャトレーゼ除くの注文 且つ 下請け運賃 <> nullの下請け運賃
            Decimal FujiEchoCharteredVehicleSubcontractSales = 0; //富士エコー・ローソン（傭車）下払い　⇒　富士エコーの注文 且つ 下請け運賃 <> nullの下請け運賃

            for (AccountingDetail__c accDetail : accountingDetails) {
                String accountCode = accDetail.InvoiceAccount__r.AccountCode__c; //取引先コード
                String parentAccountCode = null; //親取引先コード
                if (accDetail.InvoiceAccount__r.ParentId != null) {
                    parentAccountCode = accDetail.InvoiceAccount__r.Parent.AccountCode__c;
                }

                //取引先/親取引先：シャトレーゼの場合
                if (accountCode == ChateraiseAccountCode || parentAccountCode == ChateraiseAccountCode) {
                    //System.debug('★シャトレーゼ');
                    if (accDetail.AccountingType__c == '2') {
                        ChateraiseSubcontractorSales += accDetail.Amount__c; //シャトレーゼ下払い
                    } else if (accDetail.AccountingType__c == '1') {
                        ChateraiseSales += accDetail.Amount__c; //シャトレーゼ実績
                    }
                }
                //取引先/親取引先：富士エコーの場合
                else if (accountCode == FujiEchoAccountCode || parentAccountCode == FujiEchoAccountCode) {
                    //System.debug('★富士エコー');
                    if (accDetail.AccountingType__c == '2') {
                        CharteredVehicleSubcontractorSales += accDetail.Amount__c; //傭車全体（シャト除く）下払い
                        FujiEchoCharteredVehicleSubcontractSales += accDetail.Amount__c; //富士エコー・ローソン（傭車）下払い
                    } else if (accDetail.AccountingType__c == '1') {
                        if (accDetail.OrderHeader__c != null) {
                            //注文<>null
                            if (accDetail.OrderHeader__r.SubcontractFee__c == null) {
                                MARUSMfjVehicleSales += accDetail.Amount__c; //マルエス（MFJ車）実績
                                FujiEchoMfjVehicleSales += accDetail.Amount__c; //富士エコー・ローソン（MFJ車）実績
                            } else {
                                CharteredVehicleSales += accDetail.Amount__c; //傭車全体（シャト除く）実績
                                FujiEchoCharteredVehicleSales += accDetail.Amount__c; //富士エコー・ローソン（傭車）実績
                            }
                        }
                    }
                }
                //取引先/親取引先：他の場合
                else {
                    //System.debug('★シャトレーゼと富士エコーの以外');
                    if (accDetail.AccountingType__c == '2') {
                        CharteredVehicleSubcontractorSales += accDetail.Amount__c; //傭車全体（シャト除く）下払い
                    } else if (accDetail.AccountingType__c == '1') {
                        if (accDetail.OrderHeader__c != null) {
                            //注文<>null
                            if (accDetail.OrderHeader__r.SubcontractFee__c == null) {
                                MARUSMfjVehicleSales += accDetail.Amount__c; //マルエス（MFJ車）実績
                            } else {
                                CharteredVehicleSales += accDetail.Amount__c; //傭車全体（シャト除く）実績
                            }
                        }
                    }
                }
            } ////for

            ShippingSalesReport__c shippingSalesReport;

            if (ShippingSalesReportMap.containsKey(keyDate)) {
                shippingSalesReport = ShippingSalesReportMap.get(keyDate);
            } else {
                shippingSalesReport = new ShippingSalesReport__c();
                shippingSalesReport.Date__c = keyDate;
                if (ObjectiveManagementMap.containsKey(keyDate.month())) {
                    shippingSalesReport.ObjectiveManagement__c = ObjectiveManagementMap.get(keyDate.month()); //目標管理Idを付与
                }
                ShippingSalesReportMap.put(keyDate, shippingSalesReport);
            }

            shippingSalesReport.MARUSMfjVehicleSales__c = MARUSMfjVehicleSales; //マルエス（MFJ車）実績
            shippingSalesReport.ChateraiseSales__c = ChateraiseSales; //シャトレーゼ実績
            shippingSalesReport.FujiEchoMfjVehicleSales__c = FujiEchoMfjVehicleSales; //富士エコー・ローソン（MFJ車）実績
            shippingSalesReport.CharteredVehicleSales__c = CharteredVehicleSales; //傭車全体（シャト除く）実績
            shippingSalesReport.FujiEchoCharteredVehicleSales__c = FujiEchoCharteredVehicleSales; //富士エコー・ローソン（傭車）実績
            shippingSalesReport.ChateraiseSubcontractorSales__c = ChateraiseSubcontractorSales; //シャトレーゼ下払い
            shippingSalesReport.CharteredVehicleSubcontractorSales__c = CharteredVehicleSubcontractorSales; //傭車全体（シャト除く）下払い
            shippingSalesReport.FujiEchoCharteredVehicleSubcontractSales__c = FujiEchoCharteredVehicleSubcontractSales; //富士エコー・ローソン（傭車）下払い
        } ////for

        List<ShippingSalesReport__c> shippingSalesReportUpsertList = new List<ShippingSalesReport__c>(
            ShippingSalesReportMap.values()
        );

        Savepoint sp;
        try {
            allCount += shippingSalesReportUpsertList.size(); //処理件数

            sp = Database.setSavepoint();
            Database.UpsertResult[] saveResultList = Database.upsert(shippingSalesReportUpsertList, false);

            for (Integer i = 0; i < saveResultList.size(); i++) {
                Database.UpsertResult sr = saveResultList[i];
                ShippingSalesReport__c eObj = shippingSalesReportUpsertList[i];

                if (false == sr.isSuccess()) {
                    errorCount++; //処理失敗件数累計
                    for (Database.Error err : sr.getErrors()) {
                        String errorMessage =
                            '日付：' +
                            eObj.Date__c +
                            'の運送売上実績表の作成または更新に失敗しました。' +
                            err;
                        errorMessageList.add(errorMessage);
                    }
                }
            }
            sucessCount = allCount - errorCount; //処理成功件数

            // ログの状態とメッセージを更新
            processLog.ProcessStatus__c = 'Processing'; // 処理状態
            // ログレコードを更新
            update processLog;
        } catch (Exception e) {
            Database.rollback(sp);
            errorNaiyouList.add(e.getMessage());
        }
    }

    public void finish(Database.BatchableContext BC) {
        if (0 == allCount) {
            return;
        }

        if (!errorNaiyouList.isEmpty()) {
            // 処理内容を整理する
            String errMessage = '';
            for (String msg : errorNaiyouList) {
                errMessage += msg + ';';
            }
            errMessage =
                '運送売上実績表作成バッチ実行完了' +
                datetime.now() +
                '<br /> 処理失敗<br />' +
                '処理対象日数: {' +
                allCount +
                '処理成功した日数: {' +
                sucessCount +
                '}<br />' +
                '処理失敗した日数: {' +
                errorCount +
                '}<br />' +
                'エラーメッセージ: ' +
                errMessage;

            // ログの状態とメッセージを更新
            processLog.ProcessSubject__c = System.Today().format().replace('/', '') + ': 運送売上実績表作成バッチ実行失敗'; // 処理件名
            processLog.ProcessDetails__c = errMessage; // 処理内容
            processLog.ProcessLog__c = '処理失敗'; // 処理ログ
            processLog.ProcessStatus__c = 'Error'; // 処理状態
            processLog.ToEmailGroupAddresses__c = 'OrderGroup;SystemGroup'; // 送信先の課
            // ログレコードを更新
            update processLog;
            return;
        }
        // ログを記録する
        if (errorMessageList.isEmpty()) {
            // ログの状態を更新
            processLog.ProcessStatus__c = 'Success'; // 処理状態
            processLog.ProcessLog__c = '処理成功対象処理日数: {' + allCount + '}'; // 処理ログ
            // ログレコードを更新
            update processLog;
        } else {
            // 処理内容を整理する
            String errMessage = '';
            for (String msg : errorMessageList) {
                errMessage += msg + ';';
            }
            errMessage =
                '運送売上実績表作成バッチ実行完了' +
                datetime.now() +
                '<br /> 処理失敗<br />' +
                '処理対象日数: {' +
                allCount +
                '}<br />' +
                '処理成功した日数: {' +
                sucessCount +
                '}<br />' +
                '処理失敗した日数: {' +
                errorCount +
                '}<br />' +
                'エラーメッセージ: ' +
                errMessage;

            // ログの状態とメッセージを更新
            processLog.ProcessSubject__c = System.Today().format().replace('/', '') + ': 運送売上実績表作成バッチ実行失敗'; // 処理件名
            processLog.ProcessDetails__c = errMessage; // 処理内容
            processLog.ProcessLog__c = '処理失敗'; // 処理ログ
            processLog.ProcessStatus__c = 'Error'; // 処理状態
            processLog.ToEmailGroupAddresses__c = 'OrderGroup;SystemGroup'; // 送信先の課
            // ログレコードを更新
            update processLog;
        }
    }

    /**
     * 一括処理ログのレコードを作成
     * @param log 処理ログ
     * @param subject 処理件名
     * @param message 処理内容
     * @param status 処理状態
     * @param groupAddresses 送信先の課
     * @return 一括処理ログのList
     */
    private BulkProcessLog__c logBatchStatus(
        String log,
        String subject,
        String details,
        String status,
        String groupAddresses
    ) {
        // 処理ログ
        processLog.ProcessLog__c = log;
        // 処理件名
        processLog.ProcessSubject__c = subject;
        // 処理内容
        processLog.ProcessDetails__c = details;
        // 処理分類
        processLog.ProcessType__c = BATCH_JOB_PROCESS_TYPE;
        // 処理状態
        processLog.ProcessStatus__c = status;
        // 送信先の課
        processLog.ToEmailGroupAddresses__c = groupAddresses;
        return processLog;
    }
}