force-app/main/default/objects/Account/fields/AccountCode__c.field-meta.xml
<CustomField>
    <fullName>AccountCode__c</fullName>
    <displayFormat>{0000}</displayFormat>
    <label>取引先コード</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/OrderHeader__c/OrderHeader__c.object-meta.xml
<CustomObject>
    <label>注文</label>
    <nameField>
        <label>注文#</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderHeader__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>荷主</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>注文 (荷主)</relationshipLabel>
    <relationshipName>OrderHeaderList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderHeader__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Raysheetに入力が必要な必須項目</description>
    <inlineHelpText>いずれかの条件と一致する必要があります。【荷主名※または請求先名】【マルエス(自社)】【荷主名が空のもの】</inlineHelpText>
    <label>着地</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
        <errorMessage>選択した着地はこの荷主の注文レコードでは使用できません。</errorMessage>
        <filterItems>
            <field>OriginDestination__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>OriginDestination__c.Account__r.AccountCode__c</field>
            <operation>equals</operation>
            <value>9901</value>
        </filterItems>
        <filterItems>
            <field>OriginDestination__c.Account__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>OriginDestination__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.InvoiceAccount__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OriginDestination__c</referenceTo>
    <relationshipLabel>注文 (着地)</relationshipLabel>
    <relationshipName>OrderHeaderDestinationList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderHeader__c/fields/QuantityForShippingFeeCal__c.field-meta.xml
<CustomField>
    <fullName>QuantityForShippingFeeCal__c</fullName>
    <label>運賃計算用数量</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderHeader__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>「受付」→「受付確認済」の際は受注課担当がダブルチェックする</description>
    <label>状態</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reception</fullName>
                <default>true</default>
                <label>受付</label>
            </value>
            <value>
                <fullName>ReceptionCompleted</fullName>
                <label>受付確認済み</label>
            </value>
            <value>
                <fullName>DispatchCompleted</fullName>
                <label>配車完了</label>
            </value>
            <value>
                <fullName>DeliveryCompleted</fullName>
                <label>配送完了</label>
            </value>
            <value>
                <fullName>Cancel</fullName>
                <label>キャンセル</label>
            </value>
            <value>
                <fullName>InvoiceConfirmed</fullName>
                <label>請求処理済み</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderHeader__c/fields/TransportationMode__c.field-meta.xml
<CustomField>
    <fullName>TransportationMode__c</fullName>
    <label>輸送形態</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Charter</fullName>
                <default>true</default>
                <label>チャーター便</label>
            </value>
            <value>
                <fullName>Small</fullName>
                <label>小口便</label>
            </value>
            <value>
                <fullName>AccountTransfer</fullName>
                <label>荷主横持</label>
            </value>
            <value>
                <fullName>Route</fullName>
                <label>路線便</label>
            </value>
            <value>
                <fullName>Line</fullName>
                <label>幹線便</label>
            </value>
            <value>
                <fullName>Lawson</fullName>
                <label>ローソン増便</label>
            </value>
            <value>
                <fullName>ShippingOnly</fullName>
                <label>出庫のみ</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <label>その他</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderHeader__c/fields/UnitForShippingFeeCal__c.field-meta.xml
<CustomField>
    <fullName>UnitForShippingFeeCal__c</fullName>
    <label>運賃計算用単位</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UnitForShippingFeeCal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OriginDestination__c/OriginDestination__c.object-meta.xml
<CustomObject>
    <label>発着地</label>
    <nameField>
        <label>発着地名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OriginDestination__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>荷主</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>発着地</relationshipLabel>
    <relationshipName>OriginDestinationList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OriginDestination__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>市区郡</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OriginDestination__c/fields/Prefecture__c.field-meta.xml
<CustomField>
    <fullName>Prefecture__c</fullName>
    <label>都道府県</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>北海道</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>青森県</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>岩手県</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>宮城県</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>秋田県</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>山形県</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>福島県</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>茨城県</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>栃木県</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>群馬県</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>埼玉県</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>千葉県</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>東京都</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>神奈川県</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>新潟県</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>富山県</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>石川県</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>福井県</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>山梨県</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>長野県</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>岐阜県</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>静岡県</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>愛知県</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>三重県</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>滋賀県</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>京都府</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>大阪府</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>兵庫県</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>奈良県</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>和歌山県</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OriginDestination__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>町村（町名）</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PriceTable__c/PriceTable__c.object-meta.xml
<CustomObject>
    <label>価格管理</label>
    <nameField>
        <label>価格管理名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PriceTable__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>価格管理 (荷主)</relationshipLabel>
    <relationshipName>PriceTableList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PriceTable__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>有効(手動)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PriceTable__c/fields/CarryOutDate__c.field-meta.xml
<CustomField>
    <fullName>CarryOutDate__c</fullName>
    <label>適用開始日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PriceTable__c/fields/PriceTableType__c.field-meta.xml
<CustomField>
    <fullName>PriceTableType__c</fullName>
    <label>タイプ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Charter</fullName>
                <label>チャーター便</label>
            </value>
            <value>
                <fullName>Small</fullName>
                <label>小口便</label>
            </value>
            <value>
                <fullName>Route</fullName>
                <label>路線便</label>
            </value>
            <value>
                <fullName>AccountTransfer</fullName>
                <label>荷主横持</label>
            </value>
            <value>
                <fullName>StorageFee</fullName>
                <label>保管料</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PriceTable__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>状況</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>作成中</label>
            </value>
            <value>
                <fullName>Revising</fullName>
                <label>修正中</label>
            </value>
            <value>
                <fullName>PendingApproval</fullName>
                <label>承認待ち</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>承認</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>却下</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ShippingFee__c/ShippingFee__c.object-meta.xml
<CustomObject>
    <label>運賃</label>
    <nameField>
        <displayFormat>SHF-{00000000}</displayFormat>
        <label>運賃#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ShippingFee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>価格管理の荷主を設定</description>
    <label>荷主</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>ShippingFeeMasterAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ShippingFee__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>着地</label>
    <referenceTo>OriginDestination__c</referenceTo>
    <relationshipName>ShippingFeeDestinationList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ShippingFee__c/fields/PriceTable__c.field-meta.xml
<CustomField>
    <fullName>PriceTable__c</fullName>
    <label>価格管理</label>
    <referenceTo>PriceTable__c</referenceTo>
    <relationshipName>ShippingFeeList</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/UnitForShippingFeeCal.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Case</fullName>
        <default>true</default>
        <label>ケース</label>
    </customValue>
    <customValue>
        <fullName>Pallet</fullName>
        <label>パレート</label>
    </customValue>
    <customValue>
        <fullName>Kou</fullName>
        <label>甲</label>
    </customValue>
    <customValue>
        <fullName>Ton</fullName>
        <label>トン</label>
    </customValue>
    <masterLabel>運賃計算用単位</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public with sharing class TestDataFactory {
    public static Account createAccount(String newAccountCode, Boolean doInsert) {
        // Account account = new Account(Name = 'TestAccount-' + newAccountCode, AccountCode__c = newAccountCode);
        Account account = new Account(Name = 'TestAccount-' + newAccountCode);
        if (doInsert) {
            insert account;
        }
        return account;
    }

    public static PriceTable__c createPriceTable(Id accountId, Boolean doInsert) {
        PriceTable__c priceTable = new PriceTable__c(
            Name = 'Test Price Table',
            Account__c = accountId,
            CarryOutDate__c = Date.today(),
            PriceTableType__c = 'Charter',
            Active__c = true
        );
        if (doInsert) {
            insert priceTable;
        }
        return priceTable;
    }

    public static OriginDestination__c createOriginDestination(Id accountId, Boolean doInsert) {
        OriginDestination__c originDest = new OriginDestination__c(
            Account__c = accountId,
            Prefecture__c = '19',
            City__c = 'Shibuya',
            Street__c = 'Test Street'
        );
        if (doInsert) {
            insert originDest;
        }
        return originDest;
    }

    public static OrderHeader__c createOrderHeader(
        String accountId,
        String originId,
        String destinationId,
        Boolean doInsert
    ) {
        OrderHeader__c order = new OrderHeader__c(
            QuantityForShippingFeeCal__c = 10,
            UnitForShippingFeeCal__c = 'Ton',
            TransportationMode__c = 'Charter',
            Status__c = 'Reception'
        );
        if (!String.isBlank(accountId)) {
            order.Account__c = accountId;
        }
        if (!String.isBlank(originId)) {
            order.OriginPlace__c = originId;
        }
        if (!String.isBlank(destinationId)) {
            order.Destination__c = destinationId;
        }
        if (doInsert) {
            insert order;
        }
        return order;
    }

    public static ShippingFee__c createShippingFee(
        String accountId,
        Id priceTableId,
        String destinationId,
        Boolean doInsert
    ) {
        ShippingFee__c shippingFee = new ShippingFee__c(
            PriceTable__c = priceTableId,
            MinQuantity__c = 5,
            MaxQuantity__c = 20,
            FixedFeeFlag__c = false,
            Memo__c = 'Test Memo',
            Unit__c = 'Ton',
            AncillaryWorkFee__c = 10000,
            SubcontractFee__c = 1000,
            ShippingFee__c = 5000,
            OriginPrefecture__c = '19',
            ArrivalPrefecture__c = 'Tokyo',
            ArrivalCity__c = 'Shibuya',
            ArrivalStreet__c = 'Test Street',
            Active__c = true
        );
        if (!String.isBlank(destinationId)) {
            shippingFee.Destination__c = destinationId;
        }
        if (doInsert) {
            insert shippingFee;
        }
        return shippingFee;
    }
}