force-app/main/default/objects/OrderHeader__c/OrderHeader__c.object-meta.xml
<CustomObject>
    <label>注文</label>
    <nameField>
        <label>注文#</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderHeader__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>荷主</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>注文 (荷主)</relationshipLabel>
    <relationshipName>OrderHeaderList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderHeader__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Raysheetに入力が必要な必須項目</description>
    <inlineHelpText>いずれかの条件と一致する必要があります。【荷主名※または請求先名】【マルエス(自社)】【荷主名が空のもの】</inlineHelpText>
    <label>着地</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
        <errorMessage>選択した着地はこの荷主の注文レコードでは使用できません。</errorMessage>
        <filterItems>
            <field>OriginDestination__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>OriginDestination__c.Account__r.AccountCode__c</field>
            <operation>equals</operation>
            <value>9901</value>
        </filterItems>
        <filterItems>
            <field>OriginDestination__c.Account__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>OriginDestination__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.InvoiceAccount__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OriginDestination__c</referenceTo>
    <relationshipLabel>注文 (着地)</relationshipLabel>
    <relationshipName>OrderHeaderDestinationList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderHeader__c/fields/DestinationPrefecture_F__c.field-meta.xml
<CustomField>
    <fullName>DestinationPrefecture_F__c</fullName>
    <formula>Text(Destination__r.Prefecture__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>着地都道府県</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderHeader__c/fields/OriginPlace__c.field-meta.xml
<CustomField>
    <fullName>OriginPlace__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Raysheetに入力が必要な必須項目</description>
    <inlineHelpText>いずれかの条件と一致する必要があります。【荷主名※または請求先名】【マルエス(自社)】【荷主名が空のもの】</inlineHelpText>
    <label>発地</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
        <errorMessage>選択した発地はこの荷主の注文レコードでは使用できません。</errorMessage>
        <filterItems>
            <field>OriginDestination__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>OriginDestination__c.Account__r.AccountCode__c</field>
            <operation>equals</operation>
            <value>9901</value>
        </filterItems>
        <filterItems>
            <field>OriginDestination__c.Account__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>OriginDestination__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.InvoiceAccount__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OriginDestination__c</referenceTo>
    <relationshipLabel>注文（発地）</relationshipLabel>
    <relationshipName>OrderHeaderOriginPlaceList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderHeader__c/fields/OriginPrefecture_F__c.field-meta.xml
<CustomField>
    <fullName>OriginPrefecture_F__c</fullName>
    <formula>Text( OriginPlace__r.Prefecture__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>発地都道府県</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderHeader__c/fields/QuantityForShippingFeeCal__c.field-meta.xml
<CustomField>
    <fullName>QuantityForShippingFeeCal__c</fullName>
    <label>運賃計算用数量</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderHeader__c/fields/ReceptionDatetime__c.field-meta.xml
<CustomField>
    <fullName>ReceptionDatetime__c</fullName>
    <defaultValue>now()</defaultValue>
    <label>受付日時</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OrderHeader__c/fields/ShippingFee__c.field-meta.xml
<CustomField>
    <fullName>ShippingFee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>運賃#</label>
    <referenceTo>ShippingFee__c</referenceTo>
    <relationshipLabel>注文</relationshipLabel>
    <relationshipName>OrderHeaderList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderHeader__c/fields/TransportationMode__c.field-meta.xml
<CustomField>
    <fullName>TransportationMode__c</fullName>
    <label>輸送形態</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Charter</fullName>
                <default>true</default>
                <label>チャーター便</label>
            </value>
            <value>
                <fullName>Small</fullName>
                <label>小口便</label>
            </value>
            <value>
                <fullName>AccountTransfer</fullName>
                <label>荷主横持</label>
            </value>
            <value>
                <fullName>Route</fullName>
                <label>路線便</label>
            </value>
            <value>
                <fullName>Line</fullName>
                <label>幹線便</label>
            </value>
            <value>
                <fullName>Lawson</fullName>
                <label>ローソン増便</label>
            </value>
            <value>
                <fullName>ShippingOnly</fullName>
                <label>出庫のみ</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <label>その他</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderHeader__c/fields/UnitForShippingFeeCal__c.field-meta.xml
<CustomField>
    <fullName>UnitForShippingFeeCal__c</fullName>
    <label>運賃計算用単位</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UnitForShippingFeeCal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OriginDestination__c/OriginDestination__c.object-meta.xml
<CustomObject>
    <label>発着地</label>
    <nameField>
        <label>発着地名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OriginDestination__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>荷主</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>発着地</relationshipLabel>
    <relationshipName>OriginDestinationList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OriginDestination__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>市区郡</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OriginDestination__c/fields/Prefecture__c.field-meta.xml
<CustomField>
    <fullName>Prefecture__c</fullName>
    <label>都道府県</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>北海道</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>青森県</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>岩手県</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>宮城県</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>秋田県</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>山形県</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>福島県</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>茨城県</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>栃木県</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>群馬県</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>埼玉県</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>千葉県</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>東京都</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>神奈川県</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>新潟県</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>富山県</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>石川県</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>福井県</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>山梨県</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>長野県</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>岐阜県</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>静岡県</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>愛知県</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>三重県</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>滋賀県</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>京都府</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>大阪府</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>兵庫県</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>奈良県</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>和歌山県</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OriginDestination__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>町村（町名）</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PriceTable__c/PriceTable__c.object-meta.xml
<CustomObject>
    <label>価格管理</label>
    <nameField>
        <label>価格管理名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PriceTable__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>価格管理 (荷主)</relationshipLabel>
    <relationshipName>PriceTableList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ShippingFee__c/ShippingFee__c.object-meta.xml
<CustomObject>
    <label>運賃</label>
    <nameField>
        <displayFormat>SHF-{00000000}</displayFormat>
        <label>運賃#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ShippingFee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>価格管理の荷主を設定</description>
    <label>荷主</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>ShippingFeeMasterAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ShippingFee__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>着地</label>
    <referenceTo>OriginDestination__c</referenceTo>
    <relationshipName>ShippingFeeDestinationList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ShippingFee__c/fields/OriginPrefecture__c.field-meta.xml
<CustomField>
    <fullName>OriginPrefecture__c</fullName>
    <label>都道府県（発地）</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>19</fullName>
                <default>true</default>
                <label>山梨県</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>福岡県</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ShippingFee__c/fields/PriceTable__c.field-meta.xml
<CustomField>
    <fullName>PriceTable__c</fullName>
    <label>価格管理</label>
    <referenceTo>PriceTable__c</referenceTo>
    <relationshipName>ShippingFeeList</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ShippingFee__c/fields/ShippingFee__c.field-meta.xml
<CustomField>
    <fullName>ShippingFee__c</fullName>
    <label>運賃</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/UnitForShippingFeeCal.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Case</fullName>
        <default>true</default>
        <label>ケース</label>
    </customValue>
    <customValue>
        <fullName>Pallet</fullName>
        <label>パレート</label>
    </customValue>
    <customValue>
        <fullName>Kou</fullName>
        <label>甲</label>
    </customValue>
    <customValue>
        <fullName>Ton</fullName>
        <label>トン</label>
    </customValue>
    <masterLabel>運賃計算用単位</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GetShippingFeeMaster_T.cls
@istest
public with sharing class GetShippingFeeMaster_T {
    @isTest
    public static void testPatten1CalculateShippingFee() {
        // パターン１
        // テストデータの作成
        Account testAccountDestination = TestDataFactory.createAccount('aaa', true);
        Account testAccountOrigin = TestDataFactory.createAccount('bbb', true);

        PriceTable__c testPriceTable = TestDataFactory.createPriceTable(testAccountDestination.Id, true);
        OriginDestination__c testDestination = TestDataFactory.createOriginDestination(testAccountDestination.Id, true);
        OriginDestination__c testOrigin = TestDataFactory.createOriginDestination(testAccountOrigin.Id, false);
        testOrigin.Prefecture__c = '19'; //19:山梨県
        testOrigin.City__c = '';
        testOrigin.Street__c = '';
        insert testOrigin;
        ShippingFee__c testShippingFee = TestDataFactory.createShippingFee(
            testAccountDestination.Id,
            testPriceTable.Id,
            null,
            false
        );
        testShippingFee.OriginPrefecture__c = '19';
        insert testShippingFee;
        testShippingFee.Destination__c = testDestination.Id;
        update testShippingFee;
        OrderHeader__c testOrder = TestDataFactory.createOrderHeader(
            testAccountDestination.Id,
            // testAccountOrigin.Id,
            testOrigin.Id,
            testDestination.Id,
            true
        );

        String departurePrefecture = testOrder.OriginPlace__r.Prefecture__c;
        // 発着地を逆転する
        OrderHeader__c testOrder2 = TestDataFactory.createOrderHeader(
            // testAccountDestination.Id,
            testAccountOrigin.Id,
            testDestination.Id,
            testOrigin.Id,
            true
        );
        List<OrderHeader__c> oh = [
            SELECT
                Id,
                OriginPrefecture_F__c,
                DestinationPrefecture_F__c,
                Destination__c,
                QuantityForShippingFeeCal__c,
                UnitForShippingFeeCal__c,
                Account__c,
                OriginPlace__c,
                TransportationMode__c,
                ReceptionDatetime__c,
                ShippingCompany__c
            FROM OrderHeader__c
            ORDER BY CreatedDate
            LIMIT 200
        ];
        Test.startTest();
        List<ShippingFee__c> result = GetShippingFeeMaster.calculateShippingFee(oh);
        Test.stopTest();

        // 検証
        Assert.isNotNull(result, '結果がnullであってはならない');
        Assert.areEqual(2, result.size(), '2注文なので、2件の運賃データが返されるべき');
        Assert.areEqual(testShippingFee.ShippingFee__c, result[0].ShippingFee__c, '運賃が一致するべき');
        Assert.areEqual(testShippingFee.ShippingFee__c, result[0].ShippingFee__c, '運賃が一致するべき');
    }

    @isTest
    static void testPatten2CalculateShippingFee() {
        // パターン２
        // テストデータの作成
        Account testAccountDestination = TestDataFactory.createAccount('aaa', true);
        Account testAccountOrigin = TestDataFactory.createAccount('bbb', true);

        PriceTable__c testPriceTable = TestDataFactory.createPriceTable(testAccountDestination.Id, true);
        OriginDestination__c testDestination = TestDataFactory.createOriginDestination(testAccountDestination.Id, true);
        testDestination.Prefecture__c = '19';
        update testDestination;
        OriginDestination__c testOrigin = TestDataFactory.createOriginDestination(testAccountOrigin.Id, false);
        testOrigin.Prefecture__c = '19';
        testOrigin.City__c = '';
        testOrigin.Street__c = '';
        insert testOrigin;
        ShippingFee__c testShippingFee = TestDataFactory.createShippingFee(
            testAccountDestination.Id,
            testPriceTable.Id,
            null, // testDestination.Id,
            true
        );
        testShippingFee.Destination__c = testDestination.Id;
        update testShippingFee;
        OrderHeader__c testOrder = TestDataFactory.createOrderHeader(
            testAccountDestination.Id,
            testDestination.Id,
            testOrigin.Id,
            true
        );
        // // 発着地を逆転する
        // OrderHeader__c testOrder2 = TestDataFactory.createOrderHeader(
        //     testAccountDestination.Id,
        //     testOrigin.Id,
        //     testDestination.Id,
        //     true
        // );

        Test.startTest();
        List<ShippingFee__c> result = GetShippingFeeMaster.calculateShippingFee(
            // new List<OrderHeader__c>{ testOrder, testOrder2 }
            new List<OrderHeader__c>{ testOrder }
        );
        Test.stopTest();

        // 検証
        Assert.isNotNull(result, '結果がnullであってはならない');
        Assert.areEqual(1, result.size(), '2注文なので、2件の運賃データが返されるべき');
        Assert.areEqual(testShippingFee.ShippingFee__c, result[0].ShippingFee__c, '運賃が一致するべき');
    }

    @isTest
    static void testPatten34CalculateShippingFee() {
        // パターン3、パターン4
        // テストデータの作成
        Account testAccountDestination = TestDataFactory.createAccount('aaa', true);
        Account testAccountOrigin = TestDataFactory.createAccount('bbb', true);

        PriceTable__c testPriceTable = TestDataFactory.createPriceTable(testAccountDestination.Id, true);
        OriginDestination__c testDestination = TestDataFactory.createOriginDestination(testAccountDestination.Id, true);
        OriginDestination__c testOrigin = TestDataFactory.createOriginDestination(testAccountOrigin.Id, false);
        testOrigin.Prefecture__c = '福岡県';
        testOrigin.City__c = '';
        testOrigin.Street__c = '';
        insert testOrigin;
        // 運賃作成:着地IDがない、着地詳細情報が一致している
        ShippingFee__c testShippingFee = TestDataFactory.createShippingFee(
            testAccountDestination.Id,
            testPriceTable.Id,
            null,
            true
        );

        // 注文作成 パターン3
        OrderHeader__c testOrder = TestDataFactory.createOrderHeader(
            testAccountDestination.Id,
            null,
            testDestination.Id,
            true
        );
        // 発着地を逆転する パターン4
        OrderHeader__c testOrder2 = TestDataFactory.createOrderHeader(
            testAccountDestination.Id,
            testDestination.Id,
            testOrigin.Id,
            true
        );

        Test.startTest();
        List<ShippingFee__c> result = GetShippingFeeMaster.calculateShippingFee(
            new List<OrderHeader__c>{ testOrder, testOrder2 }
        );
        Test.stopTest();

        // 検証
        Assert.isNotNull(result, '結果がnullであってはならない');
        Assert.areEqual(2, result.size(), '運賃計算できる注文2件なので、2件の運賃データが返されるべき');
        Assert.areEqual(testShippingFee.ShippingFee__c, result[0].ShippingFee__c, '運賃が一致するべき');
    }

    @isTest
    static void testPatten35CalculateShippingFee() {
        // パターン3、パターン5
        // テストデータの作成
        Account testAccountDestination = TestDataFactory.createAccount('aaa', true);
        Account testAccountOrigin = TestDataFactory.createAccount('bbb', true);

        PriceTable__c testPriceTable = TestDataFactory.createPriceTable(testAccountDestination.Id, true);
        OriginDestination__c testDestination = TestDataFactory.createOriginDestination(testAccountDestination.Id, false);
        testDestination.Street__c = '';
        insert testDestination;
        OriginDestination__c testOrigin = TestDataFactory.createOriginDestination(testAccountOrigin.Id, false);
        testOrigin.Prefecture__c = '福岡県';
        testOrigin.City__c = '';
        testOrigin.Street__c = '';
        insert testOrigin;
        // 運賃作成:着地IDがない、着地詳細情報が一致している
        ShippingFee__c testShippingFee = TestDataFactory.createShippingFee(
            testAccountDestination.Id,
            testPriceTable.Id,
            null,
            true
        );

        // 注文作成 パターン3
        OrderHeader__c testOrder = TestDataFactory.createOrderHeader(
            testAccountDestination.Id,
            null,
            testDestination.Id,
            true
        );
        // 発着地を逆転する パターン5
        OrderHeader__c testOrder2 = TestDataFactory.createOrderHeader(
            testAccountDestination.Id,
            testDestination.Id,
            testOrigin.Id,
            true
        );

        Test.startTest();
        List<ShippingFee__c> result = GetShippingFeeMaster.calculateShippingFee(
            new List<OrderHeader__c>{ testOrder, testOrder2 }
        );
        Test.stopTest();

        // 検証
        Assert.isNotNull(result, '結果がnullであってはならない');
        Assert.areEqual(2, result.size(), '運賃計算できる注文2件なので、2件の運賃データが返されるべき');
        Assert.areEqual(testShippingFee.ShippingFee__c, result[0].ShippingFee__c, '運賃が一致するべき');
    }

    @isTest
    static void testPatten36CalculateShippingFee() {
        // パターン3、パターン6
        // テストデータの作成
        Account testAccountDestination = TestDataFactory.createAccount('aaa', true);
        Account testAccountOrigin = TestDataFactory.createAccount('bbb', true);

        PriceTable__c testPriceTable = TestDataFactory.createPriceTable(testAccountDestination.Id, true);
        OriginDestination__c testDestination = TestDataFactory.createOriginDestination(testAccountDestination.Id, false);
        testDestination.City__c = '';
        testDestination.Street__c = '';
        insert testDestination;
        OriginDestination__c testOrigin = TestDataFactory.createOriginDestination(testAccountOrigin.Id, false);
        testOrigin.Prefecture__c = '福岡県';
        testOrigin.City__c = '';
        testOrigin.Street__c = '';
        insert testOrigin;
        // 運賃作成:着地IDがない、着地詳細情報が一致している
        ShippingFee__c testShippingFee = TestDataFactory.createShippingFee(
            testAccountDestination.Id,
            testPriceTable.Id,
            null,
            true
        );

        // 注文作成 パターン3
        OrderHeader__c testOrder = TestDataFactory.createOrderHeader(
            testAccountDestination.Id,
            null,
            testDestination.Id,
            true
        );
        // 発着地を逆転する パターン6
        OrderHeader__c testOrder2 = TestDataFactory.createOrderHeader(
            testAccountDestination.Id,
            testDestination.Id,
            testOrigin.Id,
            true
        );

        Test.startTest();
        List<ShippingFee__c> result = GetShippingFeeMaster.calculateShippingFee(
            new List<OrderHeader__c>{ testOrder, testOrder2 }
        );
        Test.stopTest();

        // 検証
        Assert.isNotNull(result, '結果がnullであってはならない');
        Assert.areEqual(2, result.size(), '運賃計算できる注文2件なので、2件の運賃データが返されるべき');
        Assert.areEqual(testShippingFee.ShippingFee__c, result[0].ShippingFee__c, '運賃が一致するべき');
    }

    @isTest
    static void testPatten37CalculateShippingFee() {
        // パターン3、パターン7
        // テストデータの作成
        Account testAccountDestination = TestDataFactory.createAccount('aaa', true);
        Account testAccountOrigin = TestDataFactory.createAccount('bbb', true);
        Account testAccountDestinationFalse = TestDataFactory.createAccount('ccc', true);

        PriceTable__c testPriceTable = TestDataFactory.createPriceTable(testAccountDestination.Id, true);
        OriginDestination__c testDestination = TestDataFactory.createOriginDestination(testAccountDestination.Id, true);
        OriginDestination__c testDestinationFalse = TestDataFactory.createOriginDestination(
            testAccountDestinationFalse.Id,
            false
        );
        testDestinationFalse.Prefecture__c = 'XXXXX';
        testDestinationFalse.City__c = 'XXXX';
        testDestinationFalse.Street__c = 'XXX';
        insert testDestinationFalse;
        OriginDestination__c testOrigin = TestDataFactory.createOriginDestination(testAccountOrigin.Id, false);
        testOrigin.Prefecture__c = '福岡県';
        testOrigin.City__c = '';
        testOrigin.Street__c = '';
        insert testOrigin;
        // 運賃作成:着地IDがない、着地詳細情報が一致している
        ShippingFee__c testShippingFee = TestDataFactory.createShippingFee(
            testAccountDestination.Id,
            testPriceTable.Id,
            null,
            true
        );

        // 注文作成 パターン3
        OrderHeader__c testOrder = TestDataFactory.createOrderHeader(
            testAccountDestinationFalse.Id,
            null,
            testDestinationFalse.Id,
            true
        );
        // 発着地を逆転する パターン7
        OrderHeader__c testOrder2 = TestDataFactory.createOrderHeader(
            testAccountDestinationFalse.Id,
            testDestinationFalse.Id,
            testOrigin.Id,
            true
        );

        Test.startTest();
        List<ShippingFee__c> result = GetShippingFeeMaster.calculateShippingFee(
            new List<OrderHeader__c>{ testOrder, testOrder2 }
        );
        Test.stopTest();

        // 検証
        Assert.isNotNull(result, '結果がnullであってはならない');
        Assert.areEqual(2, result.size(), '運賃計算できる注文2件なので、2件の運賃データが返されるべき');
        Assert.areEqual(null, result[0].ShippingFee__c, '運賃が取得できない');
    }
}