force-app/main/default/objects/OriginDestination__c/OriginDestination__c.object-meta.xml
<CustomObject>
    <label>発着地</label>
    <nameField>
        <label>発着地名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OriginDestination__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>荷主</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>発着地</relationshipLabel>
    <relationshipName>OriginDestinationList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OriginDestination__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>市区郡</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OriginDestination__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>緯度</label>
    <precision>10</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OriginDestination__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>経度</label>
    <precision>11</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OriginDestination__c/fields/Prefecture__c.field-meta.xml
<CustomField>
    <fullName>Prefecture__c</fullName>
    <label>都道府県</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>北海道</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>青森県</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>岩手県</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>宮城県</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>秋田県</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>山形県</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>福島県</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>茨城県</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>栃木県</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>群馬県</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>埼玉県</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>千葉県</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>東京都</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>神奈川県</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>新潟県</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>富山県</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>石川県</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>福井県</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>山梨県</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>長野県</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>岐阜県</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>静岡県</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>愛知県</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>三重県</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>滋賀県</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>京都府</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>大阪府</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>兵庫県</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>奈良県</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>和歌山県</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OriginDestination__c/fields/PrefectureLabel_F__c.field-meta.xml
<CustomField>
    <fullName>PrefectureLabel_F__c</fullName>
    <formula>CASE(
    Prefecture__c,
    &quot;1&quot;, &quot;北海道&quot;,
    &quot;2&quot;, &quot;青森県&quot;,
    &quot;3&quot;, &quot;岩手県&quot;,
    &quot;4&quot;, &quot;宮城県&quot;,
    &quot;5&quot;, &quot;秋田県&quot;,
    &quot;6&quot;, &quot;山形県&quot;,
    &quot;7&quot;, &quot;福島県&quot;,
    &quot;8&quot;, &quot;茨城県&quot;,
    &quot;9&quot;, &quot;栃木県&quot;,
    &quot;10&quot;, &quot;群馬県&quot;,
    &quot;11&quot;, &quot;埼玉県&quot;,
    &quot;12&quot;, &quot;千葉県&quot;,
    &quot;13&quot;, &quot;東京都&quot;,
    &quot;14&quot;, &quot;神奈川県&quot;,
    &quot;15&quot;, &quot;新潟県&quot;,
    &quot;16&quot;, &quot;富山県&quot;,
    &quot;17&quot;, &quot;石川県&quot;,
    &quot;18&quot;, &quot;福井県&quot;,
    &quot;19&quot;, &quot;山梨県&quot;,
    &quot;20&quot;, &quot;長野県&quot;,
    &quot;21&quot;, &quot;岐阜県&quot;,
    &quot;22&quot;, &quot;静岡県&quot;,
    &quot;23&quot;, &quot;愛知県&quot;,
    &quot;24&quot;, &quot;三重県&quot;,
    &quot;25&quot;, &quot;滋賀県&quot;,
    &quot;26&quot;, &quot;京都府&quot;,
    &quot;27&quot;, &quot;大阪府&quot;,
    &quot;28&quot;, &quot;兵庫県&quot;,
    &quot;29&quot;, &quot;奈良県&quot;,
    &quot;30&quot;, &quot;和歌山県&quot;,
    &quot;31&quot;, &quot;鳥取県&quot;,
    &quot;32&quot;, &quot;島根県&quot;,
    &quot;33&quot;, &quot;岡山県&quot;,
    &quot;34&quot;, &quot;広島県&quot;,
    &quot;35&quot;, &quot;山口県&quot;,
    &quot;36&quot;, &quot;徳島県&quot;,
    &quot;37&quot;, &quot;香川県&quot;,
    &quot;38&quot;, &quot;愛媛県&quot;,
    &quot;39&quot;, &quot;高知県&quot;,
    &quot;40&quot;, &quot;福岡県&quot;,
    &quot;41&quot;, &quot;佐賀県&quot;,
    &quot;42&quot;, &quot;長崎県&quot;,
    &quot;43&quot;, &quot;熊本県&quot;,
    &quot;44&quot;, &quot;大分県&quot;,
    &quot;45&quot;, &quot;宮崎県&quot;,
    &quot;46&quot;, &quot;鹿児島県&quot;,
    &quot;47&quot;, &quot;沖縄県&quot;,
    &quot;&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>都道府県（ラベル）</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OriginDestination__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>町村（町名）</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MapAPIHandler_T.cls
@isTest
global with sharing class MapAPIHandler_T {
    global class MapAPIHandlerCalloutMock implements HttpCalloutMock {
        global HTTPResponse respond(HTTPRequest req) {
            String endpoint = req.getEndpoint();
            // Mock レスポンス
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            if (endpoint.contains('error_test')) {
                // エラーテストの場合
                res.setBody('{"status":"ERROR", "results": [], "error_message":"Mock Error"}');
                res.setStatusCode(400);
            } else {
                // 成功結果の場合
                res.setBody(
                    '{"status":"OK", "results": [{"geometry": {"location": {"lat": 90.12345678, "lng": 180.12345678}}}]}'
                );
                res.setStatusCode(200);
            }
            return res;
        }
    }

    @TestSetup
    static void makeData() {
        Account acc = TestDataFactory.createAccount('12345', false);
        insert acc;
    }

    // 直接APIハンドラーを使用する。成功結果が取得されて、発着地の「緯度」と「経度」が設定される
    @isTest
    static void testMapAPIHandler_Handler_LatLngIsSet() {
        Decimal mockLat = 90.12345678;
        Decimal mockLng = 180.12345678;
        Test.setMock(HttpCalloutMock.class, new MapAPIHandlerCalloutMock());

        // 発着地レコードを作成
        Account acc = [SELECT Id FROM Account LIMIT 1];
        OriginDestination__c origin = new OriginDestination__c();
        origin.Account__c = acc.Id;
        origin.Prefecture__c = '1';
        insert origin;
        origin = [
            SELECT Id, Prefecture__c, City__c, Street__c, PrefectureLabel_F__c, Latitude__c, Longitude__c
            FROM OriginDestination__c
            WHERE Id = :origin.Id
            LIMIT 1
        ];
        Assert.areEqual(null, origin.Latitude__c);
        Assert.areEqual(null, origin.Longitude__c);
        origin.City__c = '習志野市';
        origin.Street__c = '津田沼２－１７－１';
        Test.startTest();
        // API 実行
        System.enqueueJob(new MapAPIHandler(origin));
        Test.stopTest();
        // 発着地の緯度と経度を取得
        origin = [SELECT Latitude__c, Longitude__c FROM OriginDestination__c WHERE Id = :origin.Id LIMIT 1];
        // 設定された緯度と経度を確認
        Assert.areEqual(mockLat, origin.Latitude__c);
        Assert.areEqual(mockLng, origin.Longitude__c);
    }

    // 発着地を作成して、フローにてAPIハンドラーを使用する。成功結果が取得されて、発着地の「緯度」と「経度」が設定される
    @isTest
    static void testMapAPIHandler_FlowInsert_LatLngIsSet() {
        Decimal mockLat = 90.12345678;
        Decimal mockLng = 180.12345678;
        Test.setMock(HttpCalloutMock.class, new MapAPIHandlerCalloutMock());

        // 発着地レコードを作成
        Account acc = [SELECT Id FROM Account LIMIT 1];
        OriginDestination__c origin = new OriginDestination__c();
        origin.Account__c = acc.Id;
        origin.Prefecture__c = '1';
        origin.City__c = '習志野市';
        origin.Street__c = '津田沼２－１７－１';
        Test.startTest();
        // API 実行
        insert origin;
        Test.stopTest();
        // 発着地の緯度と経度を取得
        origin = [SELECT Latitude__c, Longitude__c FROM OriginDestination__c WHERE Id = :origin.Id LIMIT 1];
        // 設定された緯度と経度を確認
        Assert.areEqual(mockLat, origin.Latitude__c);
        Assert.areEqual(mockLng, origin.Longitude__c);
    }

    // 発着地を更新して、フローにてAPIハンドラーを使用する。成功結果が取得されて、発着地の「緯度」と「経度」が設定される
    @isTest
    static void testMapAPIHandler_FlowUpdate_LatLngIsSet() {
        Decimal mockLat = 90.12345678;
        Decimal mockLng = 180.12345678;
        Test.setMock(HttpCalloutMock.class, new MapAPIHandlerCalloutMock());

        // 発着地レコードを作成
        Account acc = [SELECT Id FROM Account LIMIT 1];
        OriginDestination__c origin = new OriginDestination__c();
        origin.Account__c = acc.Id;
        origin.Prefecture__c = '1';
        insert origin;
        // 発着地の緯度と経度が設定されないことを確認。
        origin = [
            SELECT Id, Prefecture__c, City__c, Street__c, PrefectureLabel_F__c, Latitude__c, Longitude__c
            FROM OriginDestination__c
            WHERE Id = :origin.Id
            LIMIT 1
        ];
        Assert.areEqual(null, origin.Latitude__c);
        Assert.areEqual(null, origin.Longitude__c);
        // 発着地の住所情報を更新
        origin.City__c = '習志野市';
        origin.Street__c = '津田沼２－１７－１';
        Test.startTest();
        // API 実行
        update origin;
        Test.stopTest();
        // 発着地の緯度と経度を取得
        origin = [SELECT Latitude__c, Longitude__c FROM OriginDestination__c WHERE Id = :origin.Id LIMIT 1];
        // 設定された緯度と経度を確認
        Assert.areEqual(mockLat, origin.Latitude__c);
        Assert.areEqual(mockLng, origin.Longitude__c);
    }

    // 住所情報が不足している。発着地の緯度と経度が設定されない。
    @isTest
    static void testMapAPIHandler_AddressMissing_LatLngIsNotSet() {
        Test.setMock(HttpCalloutMock.class, new MapAPIHandlerCalloutMock());

        // 発着地レコードを作成
        Account acc = [SELECT Id FROM Account LIMIT 1];
        OriginDestination__c origin = new OriginDestination__c();
        origin.Account__c = acc.Id;
        origin.Prefecture__c = '1';
        origin.City__c = '習志野市';
        origin.Street__c = null;
        Test.startTest();
        // API 実行
        insert origin;
        Test.stopTest();
        // 発着地の緯度と経度を取得
        origin = [SELECT Latitude__c, Longitude__c FROM OriginDestination__c WHERE Id = :origin.Id LIMIT 1];
        // 設定された緯度と経度を確認
        Assert.areEqual(null, origin.Latitude__c);
        Assert.areEqual(null, origin.Longitude__c);
    }

    // エラー処理のテスト。発着地の緯度と経度が設定されない。
    @isTest
    static void testMapAPIHandler_Error_LatLngIsNotSet() {
        Test.setMock(HttpCalloutMock.class, new MapAPIHandlerCalloutMock());

        // 発着地レコードを作成
        Account acc = [SELECT Id FROM Account LIMIT 1];
        OriginDestination__c origin = new OriginDestination__c();
        origin.Account__c = acc.Id;
        origin.Prefecture__c = '1';
        insert origin;
        origin = [
            SELECT Id, Prefecture__c, City__c, Street__c, PrefectureLabel_F__c, Latitude__c, Longitude__c
            FROM OriginDestination__c
            WHERE Id = :origin.Id
            LIMIT 1
        ];
        origin.City__c = '習志野市';
        origin.Street__c = 'error_test';
        Test.startTest();
        // API 実行
        System.enqueueJob(new MapAPIHandler(origin));
        Test.stopTest();
        // 発着地の緯度と経度を取得
        origin = [SELECT Latitude__c, Longitude__c FROM OriginDestination__c WHERE Id = :origin.Id LIMIT 1];
        // 設定された緯度と経度を確認
        Assert.areEqual(null, origin.Latitude__c);
        Assert.areEqual(null, origin.Longitude__c);
    }
}