force-app/main/default/objects/DispatchAssignDriver__c/DispatchAssignDriver__c.object-meta.xml
<CustomObject>
    <label>配車アサイン情報</label>
    <nameField>
        <displayFormat>DEA-{00000000}</displayFormat>
        <label>配車アサイン情報#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchAssignDriver__c/fields/CourseName_F__c.field-meta.xml
<CustomField>
    <fullName>CourseName_F__c</fullName>
    <formula>DispatchDetail__r.CourseName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>コース名</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DispatchAssignDriver__c/fields/DispatchDetail__c.field-meta.xml
<CustomField>
    <fullName>DispatchDetail__c</fullName>
    <label>配車明細</label>
    <referenceTo>DispatchDetail__c</referenceTo>
    <relationshipLabel>配車アサイン情報</relationshipLabel>
    <relationshipName>DispatchAssignDriverList</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DispatchAssignDriver__c/fields/DispatchVehicle__c.field-meta.xml
<CustomField>
    <fullName>DispatchVehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>配車車両</label>
    <referenceTo>DispatchVehicle__c</referenceTo>
    <relationshipLabel>配車アサイン情報</relationshipLabel>
    <relationshipName>DispatchAssignDriverList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DispatchAssignDriver__c/fields/DriverSchedule__c.field-meta.xml
<CustomField>
    <fullName>DriverSchedule__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>勤務情報</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>DriverSchedule__c.WorkStatus__c</field>
            <operation>notEqual</operation>
            <value>休み（有給）, 定休</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>DriverSchedule__c</referenceTo>
    <relationshipLabel>配車アサイン情報</relationshipLabel>
    <relationshipName>DispatchAssignDriverList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DispatchDetail__c/DispatchDetail__c.object-meta.xml
<CustomObject>
    <label>配車明細</label>
    <nameField>
        <displayFormat>DED-{00000000}</displayFormat>
        <label>配車明細#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchDetail__c/fields/CharteredVehicleNumber__c.field-meta.xml
<CustomField>
    <fullName>CharteredVehicleNumber__c</fullName>
    <label>下請け車番</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DispatchDetail__c/fields/DriverMaster__c.field-meta.xml
<CustomField>
    <fullName>DriverMaster__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>ドライバー</label>
    <referenceTo>DriverMaster__c</referenceTo>
    <relationshipLabel>配車明細</relationshipLabel>
    <relationshipName>DispatchDetailList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DispatchDetail__c/fields/Subcontractor__c.field-meta.xml
<CustomField>
    <fullName>Subcontractor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>下請け業者</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>配車明細</relationshipLabel>
    <relationshipName>DispatchDetailList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DispatchDetail__c/fields/VehiclelNumber_F__c.field-meta.xml
<CustomField>
    <fullName>VehiclelNumber_F__c</fullName>
    <formula>IF (
  ISNULL(VehicleMaster__r.Name)
  , CharteredVehicleNumber__c
  , VehicleMaster__r.Name
)</formula>
    <label>車種・車番</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DispatchDetail__c/fields/VehicleMaster__c.field-meta.xml
<CustomField>
    <fullName>VehicleMaster__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>自社車両</label>
    <referenceTo>VehicleMaster__c</referenceTo>
    <relationshipLabel>配車明細</relationshipLabel>
    <relationshipName>DispatchDetailList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DispatchDetail__c/fields/VehicleMaster_Name_F__c.field-meta.xml
<CustomField>
    <fullName>VehicleMaster_Name_F__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; +  Id , CourseName__c + &apos; &apos; + VehicleMaster__r.Name)</formula>
    <label>自社車両車番</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DispatchVehicle__c/DispatchVehicle__c.object-meta.xml
<CustomObject>
    <label>配車車両</label>
    <nameField>
        <displayFormat>DEV-{00000000}</displayFormat>
        <label>配車車両#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchVehicle__c/fields/CharteredVehicleNumber__c.field-meta.xml
<CustomField>
    <fullName>CharteredVehicleNumber__c</fullName>
    <label>傭車車番</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DispatchVehicle__c/fields/Subcontractor__c.field-meta.xml
<CustomField>
    <fullName>Subcontractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>下請け業者</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>配車車両</relationshipLabel>
    <relationshipName>DispatchVehicleList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DispatchVehicle__c/fields/VehicleMaster__c.field-meta.xml
<CustomField>
    <fullName>VehicleMaster__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>車両</label>
    <referenceTo>VehicleMaster__c</referenceTo>
    <relationshipLabel>配車車両</relationshipLabel>
    <relationshipName>DispatchVehicleList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DriverMaster__c/DriverMaster__c.object-meta.xml
<CustomObject>
    <label>ドライバーマスタ</label>
    <nameField>
        <label>ドライバー名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DriverMaster__c/fields/DeliveryDestinationTeam__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDestinationTeam__c</fullName>
    <label>所属</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LargeLicense</fullName>
                <default>true</default>
                <label>一般大型</label>
            </value>
            <value>
                <fullName>TRLicense</fullName>
                <label>一般TR</label>
            </value>
            <value>
                <fullName>ChateraiseLarge</fullName>
                <label>シャトレーゼ大型</label>
            </value>
            <value>
                <fullName>ChateraiseTR</fullName>
                <label>シャトレーゼTR</label>
            </value>
            <value>
                <fullName>McDonalds</fullName>
                <label>マック</label>
            </value>
            <value>
                <fullName>Starbucks</fullName>
                <label>スターバックス</label>
            </value>
            <value>
                <fullName>Lawson</fullName>
                <label>ローソン</label>
            </value>
            <value>
                <fullName>OfficeWork</fullName>
                <label>事務</label>
            </value>
            <value>
                <fullName>Warehouse</fullName>
                <label>倉庫</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DriverSchedule__c/DriverSchedule__c.object-meta.xml
<CustomObject>
    <label>勤務情報</label>
    <nameField>
        <label>勤務情報名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DriverSchedule__c/fields/AttendanceDateTime_F__c.field-meta.xml
<CustomField>
    <fullName>AttendanceDateTime_F__c</fullName>
    <formula>DATETIMEVALUE(Text(YEAR( Date__c )) + &apos;-&apos; +  LPAD(Text(MONTH(Date__c)), 2,&apos;0&apos;)   + &apos;-&apos; + LPAD(Text(DAY(Date__c)),2,&apos;0&apos;) + &apos; &apos; +  SUBSTITUTE( Text( AttendanceTime__c), &apos;.000&apos;, &apos;&apos;)) +9/24</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>出社日時</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DriverSchedule__c/fields/AttendanceTime__c.field-meta.xml
<CustomField>
    <fullName>AttendanceTime__c</fullName>
    <label>出勤時間</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/DriverSchedule__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>出勤日</description>
    <label>日付</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DriverSchedule__c/fields/DepartureDateTime_F__c.field-meta.xml
<CustomField>
    <fullName>DepartureDateTime_F__c</fullName>
    <formula>DATETIMEVALUE(Text(YEAR( DepartureDate__c )) + &apos;-&apos; + LPAD(Text(MONTH(Date__c)), 2,&apos;0&apos;) + &apos;-&apos; + LPAD(Text(DAY(Date__c)),2,&apos;0&apos;) + &apos; &apos; + SUBSTITUTE( Text( DepartureTime__c ), &apos;.000&apos;, &apos;&apos;)) +9/24</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>退社日時</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DriverSchedule__c/fields/DepartureTime__c.field-meta.xml
<CustomField>
    <fullName>DepartureTime__c</fullName>
    <label>退勤時間</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/DriverSchedule__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>ドライバー</label>
    <referenceTo>DriverMaster__c</referenceTo>
    <relationshipName>Drivers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DriverSchedule__c/fields/IsOvertime15Hours__c.field-meta.xml
<CustomField>
    <fullName>IsOvertime15Hours__c</fullName>
    <defaultValue>false</defaultValue>
    <label>拘束時間15h超過</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DriverSchedule__c/fields/TotalTime_F__c.field-meta.xml
<CustomField>
    <fullName>TotalTime_F__c</fullName>
    <formula>TEXT(FLOOR((DepartureTime__c - AttendanceTime__c) / 3600000)) &amp; &quot;:&quot; &amp;  
RIGHT(&quot;0&quot; &amp; TEXT(FLOOR(MOD((DepartureTime__c - AttendanceTime__c), 3600000) / 60000)), 2) &amp; &quot;:&quot; &amp;  
RIGHT(&quot;0&quot; &amp; TEXT(FLOOR(MOD((DepartureTime__c - AttendanceTime__c), 60000) / 1000)), 2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>拘束時間</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DriverSchedule__c/fields/WorkStatus__c.field-meta.xml
<CustomField>
    <fullName>WorkStatus__c</fullName>
    <label>勤務状況</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WorkDay</fullName>
                <default>true</default>
                <label>勤務</label>
            </value>
            <value>
                <fullName>DayOff</fullName>
                <label>休み（有給）</label>
            </value>
            <value>
                <fullName>WeeklyOff</fullName>
                <label>定休</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MFJSetting__mdt/MFJSetting__mdt.object-meta.xml
<CustomObject>
    <label>マルエス環境変数</label>
</CustomObject>

force-app/main/default/objects/MFJSetting__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <inlineHelpText>フラグの場合 True/False を入力してください</inlineHelpText>
    <label>値</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/VehicleMaster__c/VehicleMaster__c.object-meta.xml
<CustomObject>
    <label>車両マスタ</label>
    <nameField>
        <label>車番</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/WorkScheduleController.cls
public with sharing class WorkScheduleController {
    @AuraEnabled
    public static resBean getDrive(String startDatestr, String endDatestr, String deliveryDestinationTeam) {
        resBean resb = new resBean();
        try {
            Map<String, String> plickvalueMap = new Map<String, String>();
            for (Schema.PicklistEntry entry : DriverSchedule__c.WorkStatus__c.getDescribe().getPicklistValues()) {
                if (entry.isActive()) {
                    plickvalueMap.put(entry.getValue(), entry.getLabel());
                }
            }

            MFJSetting__mdt mc = MFJSetting__mdt.getInstance('ConsecutiveWorkingDays');
            Integer consecutiveWorkingDays = Integer.valueOf(mc.Value__c);
            Date startDate = Date.valueOf(startDatestr).adddays(-7);
            Date endDate = Date.valueOf(endDatestr);

            String soql = 'SELECT Id, Name FROM DriverMaster__c';
            if (String.isNotBlank(deliveryDestinationTeam)) {
                soql += ' WHERE DeliveryDestinationTeam__c includes (\'' + deliveryDestinationTeam + '\')';
            }
            List<DriverMaster__c> dmList = Database.query(soql);

            List<DispatchAssignDriver__c> deaList = [
                SELECT
                    Id,
                    Name,
                    DriverSchedule__c,
                    DriverSchedule__r.Driver__c,
                    DriverSchedule__r.IsOvertime15Hours__c,
                    DriverSchedule__r.TotalTime_F__c,
                    DriverSchedule__r.AttendanceDateTime_F__c,
                    DriverSchedule__r.DepartureDateTime_F__c,
                    DriverSchedule__r.Date__c,
                    DriverSchedule__r.AttendanceTime__c,
                    DriverSchedule__r.DepartureTime__c,
                    DispatchVehicle__c,
                    DispatchDetail__r.Id,
                    DispatchVehicle__r.Date__c,
                    DispatchVehicle__r.VehicleMaster__r.Name,
                    DispatchVehicle__r.Subcontractor__c,
                    DispatchVehicle__r.Subcontractor__r.Name,
                    DispatchVehicle__r.CharteredVehicleNumber__c,
                    CourseName_F__c,
                    DispatchDetail__r.VehiclelNumber_F__c,
                    DispatchDetail__r.VehicleMaster_Name_F__c
                FROM DispatchAssignDriver__c
                WHERE
                    DriverSchedule__r.Driver__c = :dmList
                    OR (DispatchVehicle__r.Subcontractor__c != NULL
                    AND DriverSchedule__r.Driver__c = NULL)
                // AND DispatchVehicle__r.Date__c >= :startDate
                // AND DispatchVehicle__r.Date__c <= :endDate
                ORDER BY DriverSchedule__r.Driver__c, DispatchVehicle__r.Subcontractor__c, DriverSchedule__r.Date__c ASC
            ];

            List<DriverSchedule__c> dsList = [
                SELECT Id, Date__c, Driver__c, Name, WorkStatus__c
                FROM DriverSchedule__c
                WHERE Date__c >= :startDate AND Date__c <= :endDate AND Driver__c = :dmList
            ];
            System.debug(dsList.size());
            Map<Id, List<DispatchAssignDriver__c>> deaMap = new Map<Id, List<DispatchAssignDriver__c>>();
            for (DispatchAssignDriver__c dea : deaList) {
                if (deaMap.containskey(dea.DriverSchedule__r.Id) == false) {
                    deaMap.put(dea.DriverSchedule__r.Id, new List<DispatchAssignDriver__c>());
                }
                deaMap.get(dea.DriverSchedule__r.Id).add(dea);
            }

            // ドライバーもしくは下請け業者をキーとした、配車車両のMapを作成

            Map<String, List<DispatchAssignDriver__c>> driverDeaMap = new Map<String, List<DispatchAssignDriver__c>>();
            Map<String, List<DispatchAssignDriver__c>> subcontractorDeaMap = new Map<String, List<DispatchAssignDriver__c>>();

            for (DispatchAssignDriver__c dea : deaList) {
                /*
                    配車アサインをループし、ドライバーもしくは下請け業者をキーにした配車アサインのリストを作成していく。
                    ドライバーをキーとする場合はdriverDeaMapに、下請け業者をキーとする場合はsubcontractorDeaMapに追加。
                    ※ドライバーは社内、下請け業者は社外による配送になるため、この二つの項目はどちらか片方のみ入力された状態になります。

                    ループ中：
                        driverDeaMapもしくはsubcontractorDeaMapに存在しないドライバー・下請け業者が入ってきた場合、新しい行を生成。
                        既に追加されていた場合、中のリストにレコードを追加する。
                */

                if (String.isNotBlank(dea.DriverSchedule__c)) {
                    if (driverDeaMap.containskey(dea.DriverSchedule__r.Driver__c) == false) {
                        driverDeaMap.put(dea.DriverSchedule__r.Driver__c, new List<DispatchAssignDriver__c>());
                    }
                    driverDeaMap.get(dea.DriverSchedule__r.Driver__c).add(dea);
                } else if (String.isBlank(deliveryDestinationTeam)) {
                    String key =
                        getStringCheckBlank(dea.DispatchVehicle__r.Subcontractor__c) +
                        getStringCheckBlank(dea.DispatchVehicle__r.CharteredVehicleNumber__c);
                    if (subcontractorDeaMap.containskey(key) == false) {
                        subcontractorDeaMap.put(key, new List<DispatchAssignDriver__c>());
                    }
                    subcontractorDeaMap.get(key).add(dea);
                }
            }
            Map<Id, List<DriverSchedule__c>> dsMap = new Map<Id, List<DriverSchedule__c>>();
            for (DriverSchedule__c ds : dsList) {
                if (dsMap.containskey(ds.Driver__c) == false) {
                    dsMap.put(ds.Driver__c, new List<DriverSchedule__c>());
                }
                dsMap.get(ds.Driver__c).add(ds);
            }

            // ドライバーの行を作成

            for (DriverMaster__c dm : dmList) {
                driveBean db = new driveBean();
                db.driverMaster = dm;
                db.masterId = dm.Id;
                db.masterName = dm.Name;
                db.cssstr = '';
                Map<String, worksceduleBean> dmDateMap = new Map<String, worksceduleBean>();
                db.worksceduleMap = dmDateMap;
                if (driverDeaMap.containskey(dm.Id)) {
                    Date d;
                    Integer i = 0;
                    DispatchAssignDriver__c olddr;
                    for (DispatchAssignDriver__c driverDea : driverDeaMap.get(dm.Id)) {
                        String keystr = dm.Id + driverDea.DriverSchedule__r.Date__c.format();
                        if (dmDateMap.containsKey(keystr) == false) {
                            dmDateMap.put(keystr, new worksceduleBean());
                        }
                        worksceduleBean wcb = dmDateMap.get(keystr);
                        if (d == null) {
                            d = driverDea.DriverSchedule__r.Date__c;
                        }
                        System.debug(driverDea.DriverSchedule__r.Date__c + '  ' + d);
                        System.debug(d.daysBetween(driverDea.DriverSchedule__r.Date__c));
                        System.debug(i);
                        if (d.daysBetween(driverDea.DriverSchedule__r.Date__c) > i) {
                            d = driverDea.DriverSchedule__r.Date__c;
                            i = 0;
                        }
                        i++;
                        if (i > consecutiveWorkingDays) {
                            wcb.overCssStr = 'overCssStr';
                        }
                        System.debug(wcb.overCssStr + consecutiveWorkingDays);
                        if (
                            olddr != null &&
                            driverDea.DriverSchedule__c != null &&
                            driverDea.DriverSchedule__r.Date__c != null &&
                            driverDea.DriverSchedule__r.Date__c.daysBetween(olddr.DriverSchedule__r.Date__c) == 1
                        ) {
                            if (
                                driverDea.DriverSchedule__r.AttendanceDateTime_F__c.getTime() -
                                olddr.DriverSchedule__r.DepartureDateTime_F__c.getTime() < 777600000
                            ) {
                                wcb.overCssStr2 = 'over9h';
                            }
                        }
                        if (
                            driverDea.DriverSchedule__r.AttendanceTime__c != null &&
                            driverDea.DriverSchedule__r.DepartureTime__c != null
                        ) {
                            Integer len = driverDea.DriverSchedule__r.TotalTime_F__c.split(':')[0].length();
                            wcb.overCssStr15 = len > 1 && driverDea.DriverSchedule__r.TotalTime_F__c > '15' ? 'over15' : '';
                        }
                        if (driverDea.DriverSchedule__c != null && driverDea.DriverSchedule__r.Date__c != null) {
                            olddr = driverDea;
                        }
                        wcb.dispatchVehicle = driverDea.DispatchVehicle__r;
                        wcb.dispatchVehiclemastername = driverDea.DispatchDetail__r.VehiclelNumber_F__c;

                        Set<Id> existingDeaIds = new Set<Id>();
                        for (DispatchAssignDriver__c existingDea : wcb.dispatchAssignDriverList) {
                            existingDeaIds.add(existingDea.Id);
                        }
                        if (deaMap.containsKey(driverDea.DriverSchedule__r.Id)) {
                            for (DispatchAssignDriver__c dea : deaMap.get(driverDea.DriverSchedule__r.Id)) {
                                if (!existingDeaIds.contains(dea.Id)) {
                                    wcb.dispatchAssignDriverList.add(dea);
                                    existingDeaIds.add(dea.Id);
                                }
                            }
                        }
                    }
                    // for (DriverSchedule__c ds : dsMap.get(dm.Id)) {
                    //     String keystr = dm.Id + ds.Date__c.format();
                    //     if (dmDateMap.containsKey(keystr) == false) {
                    //         dmDateMap.put(keystr, new worksceduleBean());
                    //     }
                    //     worksceduleBean wcb = dmDateMap.get(keystr);
                    //     wcb.driverSchedule = ds;
                    //     if (String.isNotBlank(ds.WorkStatus__c)) {
                    //         wcb.dispatchVehicleworkStatus = plickvalueMap.get(ds.WorkStatus__c);
                    //     }
                    // }
                }
                if (dsMap.containsKey(dm.Id) && dsMap.get(dm.Id).size() > 0) {
                    for (DriverSchedule__c ds : dsMap.get(dm.Id)) {
                        String keystr = dm.Id + ds.Date__c.format();
                        if (dmDateMap.containsKey(keystr) == false) {
                            dmDateMap.put(keystr, new worksceduleBean());
                        }
                        worksceduleBean wcb = dmDateMap.get(keystr);
                        wcb.driverSchedule = ds;
                        if (String.isNotBlank(ds.WorkStatus__c)) {
                            wcb.dispatchVehicleworkStatus = plickvalueMap.get(ds.WorkStatus__c);
                        }
                    }
                }
                resb.drives.add(db);
            }

            // 下請け業者の行を作成

            for (String SubcontractorId : subcontractorDeaMap.keySet()) {
                driveBean db = new driveBean();
                db.driverMaster = null;
                db.cssstr = 'nothavedmaster';
                Map<String, worksceduleBean> dmDateMap = new Map<String, worksceduleBean>();
                db.worksceduleMap = dmDateMap;
                if (subcontractorDeaMap.containskey(SubcontractorId)) {
                    for (DispatchAssignDriver__c subcontractorDea : subcontractorDeaMap.get(SubcontractorId)) {
                        db.masterId = SubcontractorId;
                        db.masterName =
                            subcontractorDea.DispatchVehicle__r.Subcontractor__r.Name +
                            '(' +
                            getStringCheckBlank(subcontractorDea.DispatchVehicle__r.CharteredVehicleNumber__c) +
                            ')';
                        String keystr = SubcontractorId + subcontractorDea.DispatchVehicle__r.Date__c.format();
                        if (dmDateMap.containsKey(keystr) == false) {
                            dmDateMap.put(keystr, new worksceduleBean());
                        }
                        worksceduleBean wcb = dmDateMap.get(keystr);
                        wcb.dispatchVehicle = subcontractorDea.DispatchVehicle__r;
                        wcb.dispatchVehiclemastername = getStringCheckBlank(
                            subcontractorDea.DispatchDetail__r.VehiclelNumber_F__c
                        );
                        if (deaMap.containsKey(subcontractorDea.DispatchDetail__r.Id)) {
                            for (DispatchAssignDriver__c dea : deaMap.get(subcontractorDea.DispatchDetail__r.Id)) {
                                wcb.dispatchAssignDriverList.add(dea);
                            }
                        }
                    }
                }
                resb.drives.add(db);
            }

            resb.issuccess = true;
            return resb;
        } catch (Exception e) {
            resb.issuccess = false;
            resb.errormessage = e.getMessage() + e.getStackTraceString();
        }
        return resb;
    }

    public static String getStringCheckBlank(String str) {
        return String.isBlank(str) ? '' : str;
    }

    public class resBean {
        @AuraEnabled
        public Boolean issuccess;
        @AuraEnabled
        public String errormessage;
        @AuraEnabled
        public List<driveBean> drives;

        resBean() {
            this.drives = new List<driveBean>();
        }
    }

    public class driveBean {
        @AuraEnabled
        public DriverMaster__c driverMaster;
        @AuraEnabled
        public String masterId;
        @AuraEnabled
        public String masterName;
        @AuraEnabled
        public String cssstr;
        @AuraEnabled
        public Map<String, worksceduleBean> worksceduleMap;
        driveBean() {
            this.worksceduleMap = new Map<String, worksceduleBean>();
        }
    }
    public class worksceduleBean {
        @AuraEnabled
        public DriverSchedule__c driverSchedule;
        @AuraEnabled
        public DispatchVehicle__c dispatchVehicle;
        @AuraEnabled
        public String dispatchVehiclemastername;
        @AuraEnabled
        public String dispatchVehicleworkStatus;
        @AuraEnabled
        public String overCssStr;
        @AuraEnabled
        public String overCssStr2;
        @AuraEnabled
        public String overCssStr15;
        @AuraEnabled
        public Date de;
        @AuraEnabled
        public List<DispatchAssignDriver__c> dispatchAssignDriverList;
        worksceduleBean() {
            this.dispatchAssignDriverList = new List<DispatchAssignDriver__c>();
            this.dispatchVehicleworkStatus = '';
            this.dispatchVehiclemastername = '';
        }
    }
}