force-app/main/default/objects/DispatchAssignDriver__c/DispatchAssignDriver__c.object-meta.xml
<CustomObject>
    <label>配車アサイン情報</label>
    <nameField>
        <displayFormat>DEA-{00000000}</displayFormat>
        <label>配車アサイン情報#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchAssignDriver__c/fields/DispatchDetail__c.field-meta.xml
<CustomField>
    <fullName>DispatchDetail__c</fullName>
    <label>配車明細</label>
    <referenceTo>DispatchDetail__c</referenceTo>
    <relationshipLabel>配車アサイン情報</relationshipLabel>
    <relationshipName>DispatchAssignDriverList</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DispatchAssignDriver__c/fields/DispatchVehicle__c.field-meta.xml
<CustomField>
    <fullName>DispatchVehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>配車車両</label>
    <referenceTo>DispatchVehicle__c</referenceTo>
    <relationshipLabel>配車アサイン情報</relationshipLabel>
    <relationshipName>DispatchAssignDriverList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DispatchAssignDriver__c/fields/DriverSchedule__c.field-meta.xml
<CustomField>
    <fullName>DriverSchedule__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>勤務情報</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>DriverSchedule__c.WorkStatus__c</field>
            <operation>notEqual</operation>
            <value>休み（有給）, 定休</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>DriverSchedule__c</referenceTo>
    <relationshipLabel>配車アサイン情報</relationshipLabel>
    <relationshipName>DispatchAssignDriverList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DispatchDetail__c/DispatchDetail__c.object-meta.xml
<CustomObject>
    <label>配車明細</label>
    <nameField>
        <displayFormat>DED-{00000000}</displayFormat>
        <label>配車明細#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchDetail__c/fields/DriverMaster__c.field-meta.xml
<CustomField>
    <fullName>DriverMaster__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>ドライバー</label>
    <referenceTo>DriverMaster__c</referenceTo>
    <relationshipLabel>配車明細</relationshipLabel>
    <relationshipName>DispatchDetailList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DispatchDetail__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <externalId>true</externalId>
    <label>一意キー（不要）</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DispatchDetail__c/fields/VehicleMaster__c.field-meta.xml
<CustomField>
    <fullName>VehicleMaster__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>自社車両</label>
    <referenceTo>VehicleMaster__c</referenceTo>
    <relationshipLabel>配車明細</relationshipLabel>
    <relationshipName>DispatchDetailList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DispatchDetail__c/fields/VehicleMaster_Name_F__c.field-meta.xml
<CustomField>
    <fullName>VehicleMaster_Name_F__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; +  Id , CourseName__c + &apos; &apos; + VehicleMaster__r.Name)</formula>
    <label>自社車両車番</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DispatchVehicle__c/DispatchVehicle__c.object-meta.xml
<CustomObject>
    <label>配車車両</label>
    <nameField>
        <displayFormat>DEV-{00000000}</displayFormat>
        <label>配車車両#</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatchVehicle__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <externalId>true</externalId>
    <label>一意キー</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DispatchVehicle__c/fields/VehicleMaster__c.field-meta.xml
<CustomField>
    <fullName>VehicleMaster__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>車両</label>
    <referenceTo>VehicleMaster__c</referenceTo>
    <relationshipLabel>配車車両</relationshipLabel>
    <relationshipName>DispatchVehicleList</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DriverMaster__c/DriverMaster__c.object-meta.xml
<CustomObject>
    <label>ドライバーマスタ</label>
    <nameField>
        <label>ドライバー名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DriverMaster__c/fields/DeliveryDestinationTeam__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDestinationTeam__c</fullName>
    <label>所属</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LargeLicense</fullName>
                <default>true</default>
                <label>一般大型</label>
            </value>
            <value>
                <fullName>TRLicense</fullName>
                <label>一般TR</label>
            </value>
            <value>
                <fullName>ChateraiseLarge</fullName>
                <label>シャトレーゼ大型</label>
            </value>
            <value>
                <fullName>ChateraiseTR</fullName>
                <label>シャトレーゼTR</label>
            </value>
            <value>
                <fullName>McDonalds</fullName>
                <label>マック</label>
            </value>
            <value>
                <fullName>Starbucks</fullName>
                <label>スターバックス</label>
            </value>
            <value>
                <fullName>Lawson</fullName>
                <label>ローソン</label>
            </value>
            <value>
                <fullName>OfficeWork</fullName>
                <label>事務</label>
            </value>
            <value>
                <fullName>Warehouse</fullName>
                <label>倉庫</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DriverMaster__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>TRAFFICS2番号を入力して下さい</inlineHelpText>
    <label>TRAFFICS2番号</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DriverSchedule__c/DriverSchedule__c.object-meta.xml
<CustomObject>
    <label>勤務情報</label>
    <nameField>
        <label>勤務情報名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DriverSchedule__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>出勤日</description>
    <label>日付</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DriverSchedule__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>ドライバー</label>
    <referenceTo>DriverMaster__c</referenceTo>
    <relationshipName>Drivers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DriverSchedule__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <description>{!Driver__c}+YYYYMMDDを設定する</description>
    <externalId>true</externalId>
    <label>一意キー</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DriverSchedule__c/fields/WorkStatus__c.field-meta.xml
<CustomField>
    <fullName>WorkStatus__c</fullName>
    <label>勤務状況</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WorkDay</fullName>
                <default>true</default>
                <label>勤務</label>
            </value>
            <value>
                <fullName>DayOff</fullName>
                <label>休み（有給）</label>
            </value>
            <value>
                <fullName>WeeklyOff</fullName>
                <label>定休</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MFJSetting__mdt/MFJSetting__mdt.object-meta.xml
<CustomObject>
    <label>マルエス環境変数</label>
</CustomObject>

force-app/main/default/objects/MFJSetting__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <inlineHelpText>フラグの場合 True/False を入力してください</inlineHelpText>
    <label>値</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/VehicleMaster__c/VehicleMaster__c.object-meta.xml
<CustomObject>
    <label>車両マスタ</label>
    <nameField>
        <label>車番</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DriverScheduleController.cls
public with sharing class DriverScheduleController {
    @AuraEnabled
    public static resBean getDrive(String startDatestr, String endDatestr, String deliveryDestinationTeam) {
        resBean resb = new resBean();
        try {
            Map<String, String> plickvalueMap = new Map<String, String>();
            for (Schema.PicklistEntry entry : DriverSchedule__c.WorkStatus__c.getDescribe().getPicklistValues()) {
                if (entry.isActive()) {
                    plickvalueMap.put(entry.getValue(), entry.getLabel());
                }
            }

            MFJSetting__mdt mc = MFJSetting__mdt.getInstance('ConsecutiveWorkingDays');
            Integer consecutiveWorkingDays = Integer.valueOf(mc.Value__c);
            Date startDate = Date.valueOf(startDatestr);
            Date endDate = Date.valueOf(endDatestr);

            String soql = 'SELECT Id, Name FROM DriverMaster__c';
            if (String.isNotBlank(deliveryDestinationTeam)) {
                soql += ' WHERE DeliveryDestinationTeam__c includes (\'' + deliveryDestinationTeam + '\')';
            }
            List<DriverMaster__c> dmList = Database.query(soql);
            List<DriverSchedule__c> dsList = [
                SELECT Id, Date__c, Driver__c, Name, WorkStatus__c
                FROM DriverSchedule__c
                WHERE Date__c >= :startDate AND Date__c <= :endDate AND Driver__c = :dmList
            ];
            Map<Id, List<DriverSchedule__c>> dsMap = new Map<Id, List<DriverSchedule__c>>();
            for (DriverSchedule__c ds : dsList) {
                if (dsMap.containskey(ds.Driver__c) == false) {
                    dsMap.put(ds.Driver__c, new List<DriverSchedule__c>());
                }
                dsMap.get(ds.Driver__c).add(ds);
            }
            Map<Id, List<DispatchAssignDriver__c>> dadMap = new  Map<Id, List<DispatchAssignDriver__c>>();
            if (dsList.size() > 0) {
                List<DispatchAssignDriver__c> dadList = [SELECT Id, DispatchDetail__r.VehicleMaster__c, DriverSchedule__c,DispatchDetail__r.VehicleMaster_Name_F__c
                    FROM DispatchAssignDriver__c WHERE DriverSchedule__c = :dsList];
                for (DispatchAssignDriver__c ds :dadList) {
                    if (dadMap.containsKey(ds.DriverSchedule__c) == false) {
                        dadMap.put(ds.DriverSchedule__c, new List<DispatchAssignDriver__c>());
                    }
                    if (String.isNotBlank(ds.DispatchDetail__c) && String.isNotBlank(ds.DispatchDetail__r.VehicleMaster__c)) {
                        dadMap.get(ds.DriverSchedule__c).add(ds);
                    }
                }
            }
            

            for (DriverMaster__c dm : dmList) {
                driveBean db = new driveBean();
                db.driverMaster = dm;
                db.masterId = dm.Id;
                db.masterName = dm.Name;
                db.cssstr = '';
                Map<String, worksceduleBean> dmDateMap = new Map<String, worksceduleBean>();
                db.worksceduleMap = dmDateMap;
                if (dsMap.containskey(dm.Id)) {
                    Date d;
                    Integer i = 0;
                    for (DriverSchedule__c ds : dsMap.get(dm.Id)) {
                        String keystr = dm.Id + ds.Date__c.format();
                        if (dmDateMap.containsKey(keystr) == false) {
                            dmDateMap.put(keystr, new worksceduleBean());
                        }
                        worksceduleBean wcb = dmDateMap.get(keystr);
                        wcb.driverSchedule = ds;
                        if (dadMap.containsKey(ds.Id)) {
                            wcb.dadList = dadMap.get(ds.Id);
                        }
                        if (String.isNotBlank(ds.WorkStatus__c)) {
                            wcb.dispatchVehicleworkStatus = plickvalueMap.get(ds.WorkStatus__c);
                        }
                    }
                }
                resb.drives.add(db);
            }
            resb.issuccess = true;
            return resb;
        } catch (Exception e) {
            resb.issuccess = false;
            resb.errormessage = e.getMessage();
        }
        return resb;
    }

    @AuraEnabled
    public static resBean saveDs(String masterid, String datestr, String status) {
        resBean rs = new resBean();
        try {
            DriverSchedule__c ds = new DriverSchedule__c();
            ds.UniqueKey__c = masterid + datestr.remove('-');
            ds.WorkStatus__c = status;
            ds.Driver__c = masterid;
            ds.Date__c = Date.valueOf(datestr);
            upsert ds UniqueKey__c;
            rs.issuccess = true;
        } catch (Exception e) {
            rs.issuccess = false;
            rs.errormessage = e.getMessage();
        }
        return rs;
    }

    public static String getStringCheckBlank(String str) {
        return String.isBlank(str) ? '' : str;
    }

    public class resBean {
        @AuraEnabled
        public Boolean issuccess;
        @AuraEnabled
        public String errormessage;
        @AuraEnabled
        public List<driveBean> drives;

        resBean() {
            this.drives = new List<driveBean>();
        }
    }

    public class driveBean {
        @AuraEnabled
        public DriverMaster__c driverMaster;
        @AuraEnabled
        public String masterId;
        @AuraEnabled
        public String masterName;
        @AuraEnabled
        public String cssstr;
        @AuraEnabled
        public Map<String, worksceduleBean> worksceduleMap;
        driveBean() {
            this.worksceduleMap = new Map<String, worksceduleBean>();
        }
    }
    public class worksceduleBean {
        @AuraEnabled
        public DriverSchedule__c driverSchedule;
        @AuraEnabled
        public DispatchVehicle__c dispatchVehicle;
        @AuraEnabled
        public String dispatchVehiclemastername;
        @AuraEnabled
        public String dispatchVehicleworkStatus;
        @AuraEnabled
        public String destr;
        @AuraEnabled
        public List<DispatchAssignDriver__c> dadList;
        worksceduleBean() {
            this.dadList = new List<DispatchAssignDriver__c>();
            this.dispatchVehicleworkStatus = '';
            this.dispatchVehiclemastername = '';
        }
    }
}